### ISSUE TITLE
Adding new fixers which are enabled by default in a preset feels like a BC break

### ISSUE THREAD

**Issue by bobthecow** [FriendsOfPHP/PHP-CS-Fixer#1038]
Every week or two builds start breaking on my PHP projects because new fixers are added to whatever preset I use. I was about to commit a `composer.json` change to lock php-cs-fixer to a specific version rather than using `~`, and I realized this is exactly what I'd do with a project that doesn't follow SemVer and might ship a BC break and cause problems for my project.

Since adding new fixers to a preset without a major version bump breaks other projects' builds, it certainly feels like that's a backwards compatibility break.

I'm not sure of the right answer though. Maybe ship versioned presets in addition to the normal one? Then `psr2` is equivalent to a `HEAD`, and `psr2-v1`, `psr2-v2`, etc are (immutable?) versions that can be relied on to not break builds going forward?

Thoughts?

**Comment by GrahamCampbell** [comment]
@bobthecow If you don't want this, then use the "none" level, and enable each fixer you want by hand.

**Comment by keradus** [comment]
@bobthecow I know this situation and as you know I am trying to help you with one of your repo about that ;)

Please consider two approaches.
#1, like Symfony (hidden behind fabbot.io)
We are using Symfony's standards (whole PSR2 + some more), all the code must be valid. If the tool that we used to watch it learn new tricks and start showing errors with our code - then cool, it should warn us and we should fix it. (That is why the new fixers are considered as new features without BC break)
So... we just set level for PHP CS Fixer.

#2, like ZF2
We are using PSR2 standards, but... don't follow all of them. We want to have full control of used fixers and not used some standard out of the box.
So... we don't use level at all, we set each fixers directly.

**Comment by ceeram** [comment]
The only option i can think of is adding all new fixers to Contrib level, and only move them to appriopriate level PSR/Symfony with major version. However i think this is very confusing that in order to get all fixers of a certain level people need to specifiy the level + additional contrib fixers.
Also it does not break your code, it might break builds, although if a new fixer was added according to a certain coding standard, your build would not break if you actually followed the standard. If your code does not adhere to a certain part of the standard, but there was no fixer yet to detect it, i dont see it as BC breaking new feature. It just happened to go by undetected in the past.

Imho semver is about the public api of the code, for users to extend implement it in their own codebase. That is what version numbers imo are about.

I don't know what is the best approach to take, but i would think the current strategy applied is correct according to semver.

**Comment by bobthecow** [comment]
When a contributor to one of my libraries opens a pull request, they may or may not be hit with a "broken build" that breaks because every single docblock in the entire project needs to be changed so that the first line of the comment ends with a period. 

It doesn't break my code, but it does break my build, sometimes for completely arbitrary reasons. I'm not saying it is (or isn't) a violation of SemVer. I'm saying it *feels* like a BC break, because that's how I have to treat it to keep it from breaking builds :)

My definition of "backwards compatible" would be something along the lines of "any commit that builds right now should be able to build at any point in the future with any version of any dependency which claims compatibility with the current version". That's the promise of SemVer, that's why we version dependencies. Right now, php-cs-fixer doesn't keep that promise. And I can't see a way — short of manually specifying the config for every single fixer — to make it work like that.

But then I'd be defining my own coding standard, and I especially don't want to do that. I want to follow Symfony. I value conformity over my own opinions about most code style things, so I'd rather just pick someone else's that I can point to and say "do that". But I also want to treat this like I do any other dependency: depend on the current version, and all compatible versions going forward, knowing that current builds will keep building. When something new and breaking is released, explicitly change my dependency to the newer version.

**Comment by stof** [comment]
@ceeram the PSR-2 level contains fixers for rules defined by PSR-2. If you enable the PSr-2 level, it means that you want **all** PSR-2 rules, even if the PHP-CS-Fixer is not yet able to cover them fully.
The same is true for the symfony level.
If a new fixer introduced at the PSR-2 level breaks your build, it means that your code *already* has CS violations, which only went undetected previously because the tool is not perfect.

The promise of the PHP-CS-Fixer project is that any fixer at the PSR-2 level is fixing stuff to match PSR-2 (same for the symfony level and the Symfony coding standards). If your code is valid according to these standards, new fixers will not fix more things than previous versions.

Your issue is that you are making the assumption that the PHP-CS-Fixer is the one defining what the Symfony coding standards are. And this assumption is wrong.

**Comment by bobthecow** [comment]
Where in the Symfony coding standard does it say that the first sentence in a docblock has to end in a period?

http://symfony.com/doc/current/contributing/code/standards.html

**Comment by ceeram** [comment]
@bobthecow then my point indeed is invalid. I had expected myself symfony level matches symfony coding standards. I wonder based on what decision the mentioned docblock fixer ended up in symfony level then. Sounds indeed more as a conventient "we want this" at symfony level, instead of actual symfony standard. In this case it would be better to add such fixers to contrib level and have users wanting to use them having to add them to their config file manually.

In phpcsfixer 2.0 the plan was to use groups instead of levels, so it would be easier to define a group with actual symfony coding standards fixers and a group of additional fixers that extend on the basic symfony group, which would be a good fit for such fixers then.

**Comment by stof** [comment]
@bobthecow it actually says it in ``here is the golden rule: Imitate the existing Symfony code.``, because the page you linked is missing lots of rules

**Comment by stof** [comment]
and the other place where it is said is in English rules: sentences end with a period (All symfony phpdoc short descriptions aim to be sentences when completed with ``This class/method/interface`` at the beginning)

**Comment by ceeram** [comment]
@stof in case of the golden rule, the missing periods in the docblocks actually needed to be fixed and would count as previously missing fixer. So in what way did the fixer break valid code? seems the code was not valid after all?

Once more im not advocating one way or the other. Just trying to find a sensible solution.

**Comment by bobthecow** [comment]
They're not sentences, though. In your head, you applied a qualifier to that rule. It's fine to enforce them as such. I don't mind using periods. But it is an unspecified rule, and it did break my builds, and this isn't an isolated example. It's systemic.

This project is creating a crappy experience for my contributors. That's why I opened this issue. I am fully capable of working around it. I just figured you might want to consider that others are having a crappy experience as well.

Carry on :)

**Comment by stof** [comment]
@bobthecow it is not unspecified. Fabien fixed the whole symfony codebase a long time ago and is asking for the period regularly on PRs (though he will probably stop asking explicitly now that the fixer is able to add them automatically and just run the fixer after merging).
However, http://symfony.com/doc/current/contributing/code/standards.html is indeed far from describing all rules (which is why they have this golden rule).

And the PHP-CS-Fixer has not been meant as a tool aimed at reporting CS issues to your contributors when they break rules (this is what PHP_Code_Sniffer was created for). This tool was created for maintainers to be able to fix coding standards easily instead of asking newcomers to understand all CS of the project when they just want to give ou a bugfix. In this regard, it makes perfect sense to have new fixers able to fix more violations of the coding standards.

**Comment by bobthecow** [comment]
Yes, it does. I agree. It makes perfect sense for new fixers to be able to fix more violations. It also makes perfect sense for new fixers not to break builds for unrelated pull requests, just because there's a fix for something (previously against the coding standard or not) which affects any file not in the current PR.

This library is being a pedantic jerk to my contributors about files they didn't even change. That's my problem. Not that the standard is a moving target, but that it's a moving target and I have to treat it like a library which doesn't follow SemVer just to keep from giving my contributors a crappy experience.

**Comment by bobthecow** [comment]
> And the PHP-CS-Fixer has not been meant as a tool aimed at reporting CS issues to your contributors when they break rules (this is what PHP_Code_Sniffer was created for).

Did anyone tell StyleCI?

**Comment by stof** [comment]
@bobthecow I'm talking about what the tool was created for, not about how it is used today.

Note that even for Symfony, we are now reporting the patch through fabbot.io (which changes a bit from the original goal of the project, indeed). But this patch only concerns files which are changed in the PR, not unrelated files. If StyleCI does not do the same, you should open an issue on them (it would be even better if they would compare the patch to the patch generated for the target branch of the PR and report issues only for changes introduced inside the PR, as scrutinizer does)

**Comment by bobthecow** [comment]
I built something similar to fabbot when I was at OpenSky, and it did the same thing. Ran phpcs against every pull request, and only reported things that were in actual lines of code touched by the PR. Definitely makes a difference. I'll bring that up with StyleCI. Until then I guess I'll lock my php-cs-fixer dependency to an explicit version :-/

**Comment by bobthecow** [comment]
Wait. That won't even work because StyleCI uses their own install. :poop:

**Comment by GrahamCampbell** [comment]
> Wait. That won't even work because StyleCI uses their own install. :poop:

@bobthecow My plan is to notify people of upcoming changes to the "presets" in styleci, which is why I don't use php-cs-fixer's levels, so I can load newer versions of php-cs-fixer for the bug fixes, without the "breaking" changes.

**Comment by GrahamCampbell** [comment]
> Until then I guess I'll lock my php-cs-fixer dependency to an explicit version :-/

A better idea would be for you to use the "none" level and add all the fixers you want yourself if you are really worried about this.

**Comment by bobthecow** [comment]
> which is why I don't use php-cs-fixer's "levels", so I can load newer versions of php-cs-fixer for the bug fixes, without the "breaking" changes.

The downside to this approach is that you're now manually maintaining a fork of the canonical level.

**Comment by bobthecow** [comment]
@GrahamCampbell if StyleCI generated patches, and only complained about lines of code touched by a PR, I think this whole thing wouldn't be as big of a deal. It'd occasionally be a little bit obnoxious, rather than being obnoxious about a huge chunk of the code base on a regular basis :)

**Comment by GrahamCampbell** [comment]
> if StyleCI generated patches, and only complained about lines of code touched by a PR

I'm not doing this on purpose. I think it's useful to get the whole picture.

**Comment by bobthecow** [comment]
> I'm not doing this on purpose. I think it's useful to get the whole picture.

That seems like the right approach for `master`, but wrong when testing pull requests.

**Comment by keradus** [comment]
Closing due to fact that discussion is dead.
I would gladly reopen it if anyone has new thoughts/solutions (but also, please take a look on #1112 first, it is quite similar)
