### ISSUE TITLE
Question: Shouldn't linter issues result in non-zero return values?

### ISSUE THREAD

**Issue by localheinz** [FriendsOfPHP/PHP-CS-Fixer#1100]
Given a configuration where

```php
protected $usingLinter = true;
```

produces the following output

```
$ vendor/bin/php-cs-fixer fix --diff --verbose
Loaded config from ".php_cs"
.............I...........................................................
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixed all files in 141.035 seconds, 36.500 MB memory used
The command "vendor/bin/php-cs-fixer fix --diff --verbose" exited with 0.
```

the line 

```
The command "vendor/bin/php-cs-fixer fix --diff --verbose" exited with 0.
```

confuses me. That is, there are files that have syntax issues.

Shouldn't this exit with a non-zero value? 
Also, it would be great if the actual files were listed in that view.

What do you think, @keradus?

**Comment by keradus** [comment]
The syntax of file is not supported by PHP CS Fixer when running on user's PHP version.
This can happen in two situations:
- file has syntaxes
- file is written in new sugar syntax like PHP 7 and linting it on PHP 5 fails

Due to second case I would not trigger it as error.
Same thing with failing to fix some weird code (when fixer throws an exception!) - single task failed, but process of whole tool was complete with success.

**Comment by keradus** [comment]
I see your question already has an open issue to discuss @localheinz 

Ref: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1102#issuecomment-94366579

any opinions?
