### ISSUE TITLE
Lowercasing class names

### ISSUE THREAD

**Issue by designermonkey** [FriendsOfPHP/PHP-CS-Fixer#1158]
I'm using this in conjunction with Sublime Text 3.

I have it configured to work to PSR-2. Sometimes (especially if the class is not camel case but a single word) this is making class names lowercase:

Session -> session
Database -> database
XSLTPage -> xsltpage (should be XsltPage, although this is an odd case)

**Comment by keradus** [comment]
Hi!
When you have a `Session` class, is it hold inside `session.php` file?
Due to PSR0 the class inside file must be the same as filename, therefore PSR0 rename the class name to match file. If this is the case then you should simply rename your files to fulfill PSR0, if not then please show use way to reproduce.

**Comment by designermonkey** [comment]
Aha! You know that may be it! The file is currently called `class.session.php`, although the files that are unaffected have the same naming format.

**Comment by keradus** [comment]
Glad to be helpfull. Please follow PSR0/PSR4 guidelines or disable PSR0 fixer ;)

**Comment by designermonkey** [comment]
Oh, I will be, this was the first step in a migration :D

Dariusz Rumiński wrote:
