### ISSUE TITLE
always get I - invalid file syntax

### ISSUE THREAD

**Issue by yangqi** [FriendsOfPHP/PHP-CS-Fixer#1191]
For any file I tried to fix, I always get following result and I have no idea what it meas by invalid file syntax. I am using this on windows, the command I used is below:

c:\xampp\php\php.exe C:\xampp\php\php-cs-fixer.phar fix c:\test.php --verbose --leve=psr2

I
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixed all files in 0.016 seconds, 3.750 MB memory used

**Comment by SpacePossum** [comment]
`invalid file syntax` implies the content of the file you supply; `c:\test.php` is not valid `php` code. Since it is not valid it cannot be fixed. `valid`, in this context, means `php` code that be parsed (/ tokenized) .
Could you share the content of `test.php`? It would allow for people to help you a bit more :)

Ps. please  try `--level=psr2` instead of `--leve=psr2` in your command.
