### ISSUE TITLE
Multiline docblock comment for variable

### ISSUE THREAD

**Issue by mxnr** [FriendsOfPHP/PHP-CS-Fixer#1250]
Hello!
Php-cs-fixer removes second asterisk from multiline PHP doc comment when this comment is in method:
```php
private function docMethod()
{
    /**
    * @var \stdClass
    */
    $a = $this->getClass();
}
```
Becomes =>
```php
private function docMethod()
{
    /*
    * @var \stdClass
    */
    $a = $this->getClass();
}
```
Is it expected?
Thanks!

**Comment by GrahamCampbell** [comment]
Yes, you can't have phpdoc for a variable like that. The correct formatting is:

```php
/** @var $a object */
$a = $this->getClass();
```

**Comment by mxnr** [comment]
Ok, cool, thanks!

**Comment by dereuromark** [comment]
But `/** @var $a object */` gets fixed to `/* @var $a object */` (inline comment).
Is that indended?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
That is intended if the thing following the phpdoc is not a structural element.

**Comment by GrahamCampbell** [comment]
It's illegal according to the proposed PSR spec we're following.

**Comment by Bilge** [comment]
Which PSR spec states docblocks may have a single asterisk for non-structural elements?

The offending fixer, `phpdoc_to_comment`, is supposed to convert comments that do not contain docblock tags. These comments clearly contain docblock tags and therefore should not be changed.

**Comment by SpacePossum** [comment]
>Which PSR spec states docblocks may have a single opening asterisk for non-structural elements?

none (AFAIK, but also none that does not allow it), that is not what this fixer is about

>The offending fixer, phpdoc_to_comment, is supposed to convert comments that do not contain docblock tags. 

The fixer converts "invalid" PHPDoc to comments, it should not touch comments.

>These comments clearly contain docblock tags and therefore should not be changed to regular single-asterisk comments.

Btw. just noticed;  this https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1250#issuecomment-110815055 
```
/** @var $a object */
$a = $this->getClass();
```

is not correct I think, it should be
```
/** @var \stdClass $a */
$a = $this->getClass();
```

last case should not be touched by the fixer.
The first sample of this issue also _looks_ OK to me, but I know it is not by spec (PSR5).
Please provide a sample that is fixed the wrong way.

**Comment by dereuromark** [comment]
Yes, whatever psr suggest a single /* is wrong, it must be /** (also logically^^)
It also gets parsed this way as structured doc block by tokenizing.

So to be clear:
```
/** @var \stdClass $a */
$a = $this->getClass();
```
is the correct one.

**Comment by Bilge** [comment]
Hi @SpacePossum :wave: Thanks for helping out with this issue!

In this simple example we will see the fixer removes the double asterisk.

```php
<?php

class A
{
    public function b()
    {
        foreach ([] as $c) {
            /** @var string $c */
            ++$c;
        }
    }
}
```

However, placing the annotation before the `foreach` does not cause this to happen.

```php
<?php

class A
{
    public function b()
    {
        /** @var string $c */
        foreach ([] as $c) {
            ++$c;
        }
    }
}
```

I believe it is correct to place the annotation before the `foreach`, however the way the fixer behaves is odd. Instead of removing the asterisk we would prefer the annotation to be moved to the correct line. Of course, that is not the job of this fixer, but if it's not the job of this fixer why is it making a change at all?

**Comment by SpacePossum** [comment]
Hi :)

Above the `foreach` is the "best" place as it is the place where the variable is created. That being said, I see value in the PHPDoc on the second location as well (but is not valid following [PSR5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#3-definitions); see "Example").

> the fixer behaves is odd.[...]  why is it making a change at all?

Agreed, I typically don't run this fixer for this reason. It doesn't "fix" the PHPDoc by moving it or fixing the PHPDoc, it changes it into a comment.  

@dereuromark 
>Well, whatever psr suggest a single /* is wrong, it must be /** (not only logically^^)

I don't think there is a PSR that suggest this. The fixer changes PHPDoc's not following PSR5 (either in content/layout or location) into a comment, so not because it _must_ be a comment but because the fixer doesn't like the PHPDoc.

>(normalized form)

I think that variant should be supported but I'm not sure, as I do not use this fixer.

**Comment by Bilge** [comment]
Now that I know why this is happening I don't mind it so much... previously I thought it was a bug in the fixer but it seems that, for all cases I looked at so far, it indicates the docblock is placed on the wrong line (or maybe the type and name were transposed like you identified earlier). The only problem is it's not clear for most people, from the way the fixer behaves, what the real issue is.

**Comment by Bilge** [comment]
I have posted a new (open) issue to track this. #2634
