### ISSUE TITLE
phpdoc_var_without_name - removes @var from hash descriptions

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#1352]
```php
    /** 
     * Something about the method    
     * 
     * @return array {
     *     @var int|null $visibility T_PRIVATE, T_PROTECTED or T_PUBLIC
     *     @var bool     $static
     *     @var bool     $abstract
     *     @var bool     $final
     * }
     */
```

The fixer should not remove the `@var`.
References: 
https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#7-describing-hashes
https://github.com/php-fig/fig-standards/pull/169/files#diff-9a10a11696dc38209c125ea9c57a565fR689
discussed here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1292#discussion_r36795601

**Comment by GrahamCampbell** [comment]
The issue is more that we don't have a concept of inlinedocs that's the issue.

**Comment by keradus** [comment]
And we sometimes need to handle inline docs (like `integer` -> `int`), and sometimes not (like in given example)

**Comment by GrahamCampbell** [comment]
Yeh.

**Comment by SpacePossum** [comment]
maybe this issue should be rephrased by someone we knows more about the topic.

**Comment by keradus** [comment]
It is a real issue, reopening ;)

**Comment by stof** [comment]
Well, the issue is that the library currently doesn't support the hash descriptions in its phpdoc parsing. The content of the hash description should not be considered as top-level phpdoc tags. This would allow each fixer to decide how they should treat it. The phpdoc_scalar would deal with them, the phpdoc_params would align them but separately from the top-level tags, and the phpdoc_var_without_name one would not do anything with them.

**Comment by GrahamCampbell** [comment]
Yeh, I'll work on a fix soon.

**Comment by GrahamCampbell** [comment]
Check out https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1374.
