### ISSUE TITLE
using stdin and stdout

### ISSUE THREAD

**Issue by garak** [FriendsOfPHP/PHP-CS-Fixer#1579]
Is there any change to use the fixer with stdin/stdout?
The use case is: I don't want to pass a path and get the file(s) on that path to be fixed, I want to pass a content as stdin and get the fixed content as stdout

**Comment by stof** [comment]
``php-cs-fixer fix -`` should do the work

**Comment by GrahamCampbell** [comment]
Yeh, I'm pretty sure we got this fixed a while back?

**Comment by garak** [comment]
Trying this:
``cat app/AppKernel.php > php-cs-fixer fix -``
and getting an error complaining that ``fix`` is not a file or directory

**Comment by gharlan** [comment]
`|` instead of `>`

**Comment by garak** [comment]
With pipe I'm getting this output:
``Loaded config from "/home/garak/foo/.php_cs"
   1) stdin.php
Checked all files in 0.152 seconds, 6.250 MB memory used``

And nothing else happens. The file is not fixed (but my purpose isn't that) and I don't get the fixed content as output

**Comment by SpacePossum** [comment]
`Checked` mean `dry-run` is enabled, so no fixing is done

**Comment by stof** [comment]
use the ``--diff`` option to get the diff in the output

**Comment by stof** [comment]
hmm, except that all the progress info are also sent to stdout, rather than stderr, so there is no way to get the diff alone easily

**Comment by sampablokuper** [comment]
Please can this issue be reopened? **It has not been fixed.**

@stof [wrote]:
> `cat file > php-cs-fixer fix -` should do the work

This, of course, is wrong, because `>` is an inappropriate shell redirection character to use here. Rather than piping the contents of `file` to the command `php-cs-fixer`, it would instead write the contents of `file` to a file called `php-cs-fixer`, creating the latter if necessary. But even we we use `|` instead of `>` per @gharlan 's [correction](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1579#issuecomment-162616905) of @stof's error, the functionality requested in @garak's [opening comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1579#issue-120824852) ("I don't want to pass a path and get the file(s) on that path to be fixed, I want to pass a content as stdin and get the fixed content as stdout") is still not fully present:

```
$ cat 1.php | php-cs-fixer fix --dry-run -
Loaded config default.
Using cache file ".php_cs.cache".
   1) php://stdin

Checked all files in 0.197 seconds, 12.000 MB memory used
```

Yes, PHP-CS-Fixer accepts stdin, which is good. But rather than sending to stdout, as desired, the fixed version of the PHP code that it received via stdin, PHP-CS-Fixer instead sends stdout some lines of metadata (that would more appropriately be sent to stderr).
