### ISSUE TITLE
Tag comparitor customization

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1761]
Laravel's cs is to not leave a newline between param and return tags. It would be good to have some way to configure the tag comparator.

**Comment by keradus** [comment]
Closing as there were no votes up and issue is really old.
If one want - please send a PR with proposed change.

**Comment by GrahamCampbell** [comment]
Please can we keep this open otherwise I stand even less chance of remembering than I already do.

**Comment by keradus** [comment]
I do not refuse to have it implemented, but since nobody even commented this for half a year I decided to close it. We reached 100 opened issues, I really want to get ride of most of them still this month.
Feel free to implement the change and open a PR.

**Comment by GrahamCampbell** [comment]
I'll make a private issue for myself then.

**Comment by keradus** [comment]
To be honest I have no idea what I could do with that knowledge...

**Comment by GrahamCampbell** [comment]
I guess what I'm saying is it's not encouraging contributions into this repository. I have the same issue when I close issues on the laravel/framework.

**Comment by keradus** [comment]
On the other side 100 issues raised don't encourage as well.
I am not closing everything. Just the ones that are old and only 1-2 people were involved.

Especially for that I claimed during closing that i'm not doing that as I'm against change - but because nobody want this change to happen except person who raise the issue, while still will gladly accept PR with the change.
Here, if you would really want that change you wouldn't wait for it 6+ months.
