### ISSUE TITLE
Unwanted effects of the no_extra_consecutive_blank_lines fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1931]
We should allow whitespace where the next token is a comment, such as in Laravel config files:

![image](https://cloud.githubusercontent.com/assets/2829600/15630078/38c11100-2524-11e6-8482-ac4408eed05e.png)

**Comment by GrahamCampbell** [comment]
I don't want that change to happen, but I do want every other change by the fixer to happen.

**Comment by SpacePossum** [comment]
why not configure the fixer without `'extra'` (on master/2.x) for the config files?

**Comment by GrahamCampbell** [comment]
> why not configure the fixer without 'extra' (on master/2.x) for the config files?

I can't. That's what I want to do, I want to enable `return`, but that makes this bad change.

**Comment by keradus** [comment]
Closing as there were no votes up and issue is really old.

**Comment by GrahamCampbell** [comment]
This issue is not exactly old?

**Comment by GrahamCampbell** [comment]
And the bug remains?

**Comment by keradus** [comment]
Apparently only you treat it like a bug. I'm happy to not have that pointless line and exception to the rule. 
I do not refuse to have it implemented, but since nobody even commented this for 3 months I decided to close it. We reached 100 opened issues, I really want to get ride of most of them still this month.
Feel free to implement the change to let the behaviour be configurable, then open a PR.
