### ISSUE TITLE
anonymous functions and brackets

### ISSUE THREAD

**Issue by jaszczurek** [FriendsOfPHP/PHP-CS-Fixer#1943]
why:
```php
function (int $foo) use($bar): string {
    [body]
}
```
but:
```php
function (int $foo): string
{
    [body]
}
```

**Comment by SpacePossum** [comment]
Indeed https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#6-closures examples show the first sample you provided is correct.
Didn't check but my guess this is done incorrectly because of the return type statement, which we don't support completely yet.
Thanks for reporting!

**Comment by SpacePossum** [comment]
To clarify, the `why` is because we follow PSR 2 to states the braces should be placed like that. So I miss judged this issue and it is not bug after all.

**Comment by keradus** [comment]
the second part:
```php
function (int $foo): string
{
    [body]
}
```

should be converted to
```php
function (int $foo): string {
    [body]
}
```

if I get @jaszczurek right that's the bug.
@jaszczurek , could you confirm please? or extend your report?
Also, please provide version you are using

**Comment by jaszczurek** [comment]
Fuck, my bad :(
It was on 1.11.2, on 1.11.4 works perfectly (I should use "selfupdate" more often).

**Comment by SpacePossum** [comment]
thanks for the feedback @jaszczurek :+1:
