### ISSUE TITLE
Add CLI Option to Disable Cache 

### ISSUE THREAD

**Issue by huebs** [FriendsOfPHP/PHP-CS-Fixer#1948]
I'd love to be able to disable caching using a command line option (e.g. `--no-cache`). I'm glad to implement this feature myself but wanted to run it by the community first.

My use case is this: Most of my repositories contain a `.php_cs` file with the caching feature enabled. I code in PHPStorm. I have two [External Tools](http://tzfrs.de/2015/01/automatically-format-code-to-match-psr-standards-with-phpstorm/) set up: one checks all project files, the other checks only the current file. When the "current file" tool is run, the cache file gets hoses so that the next time the "all files" tool is run, it has to recheck _every_ file.

I see two solutions to this problem:

  1. **The hard way:** enhance the caching mechanism so that it retains data for files not currently being checked. This seems like more work than it's worth and error prone.
  2. **The easy way:** add my proposed `--no-cache` option to conditionally disable caching when checking only one file. The downside to this solution is that the next time the tool runs with caching enabled, the files that have already been fixed individually will be rescanned. However, this is a much smaller performance penalty than having to start from scratch like the tool currently does.

Questions:

  - Is there an existing solution to my problem that I'm missing?
  - Is my problem already (or planned to be) addressed in version 2?
  - What do you think of my proposed solution?
  - Can it be added to the 1.* branch or should it wait for version 2?

**Comment by keradus** [comment]
kuhl AUGENOPTIK





Hello.
First of all thak you for your post.
It's really good organised and it was nice to read it.

It's great that you are aware of upcoming 2.0 version. We have recently release 2.0.0-alpha, which you could give a try.

`Easy way` solution was implemented on 2.x line and it's `--using-cache` CLI parameter that will override setting from config file.
Also, `hard way` was implemented on 2.x line.

`Hard way` solution made easy way would break BC for 1.x line, that's why we done it for 2.x. It could be done for 1.x only with a feature switch and having new behaviour disabled by default.
`Easy way` solution could be reimplemented for 1.x line without breaking BC.

After said that, currently there is no plan to made any of that changes for 1.x line, as whole caching was grately refactored on 2.x line to made it work a lot better, breaking a lot of BC in the meantime. 

Also, the current stable version is 1.11, 1.12 is on it's way and 1.12.x is planned to be the last 1.x version we will release, as 2.x is very close. (Like put what is possible for 1.12, release 2.0, then maintain 1.12.x for a while but drop it very soon)

**Comment by huebs** [comment]
Thanks for taking the time to respond. It's great to hear this has already been addressed. I'll definitely take a look at the 2.x branch when I have a chance.

**Comment by keradus** [comment]
In that case I'm closing the issue ;)
