### ISSUE TITLE
Access type modifiers will not be fixed correctly

### ISSUE THREAD

**Issue by markuspoerschke** [FriendsOfPHP/PHP-CS-Fixer#205]
``The following core will not be fixed correctly by php-cs-fixer:

``` PHP
class MyClass {
    protected
    function myFunction($param) 
    {
        // ... some code here
    }
}
```

will become:

``` PHP
class MyClass {
    protected
    public function myFunction($param) 
    {
        // ... some code here
    }
}
```

This will cause in a PHP syntax Error: `Fatal error: Multiple access type modifiers are not allowed`

**Comment by dakanji** [comment]
Google search brought me here on a variant of this issue: The double visibility was one the same line.

Not a big deal but the error message was just **"PHP Fatal error:  Multiple access type modifiers are not allowed in  on line 1444"** 

An indication of which file of about 3k files Line 1444 was located in would have been nice!

**Comment by keradus** [comment]
please raise a new issue @dakanji , to provide full issue details

**Comment by voku** [comment]
Because I saw the same error message today and the only google search result was this issue, I will add this comment for the next person who will find this. 

```Fatal error: Multiple access type modifiers are not allowed in  on line 5```

--- 

Debug via ```strace``` will help in many situations, so start with adding it in front of your current failing command, if you didn't see any output, then maybe you need to look into a sub-process (ps aux | grep php) and take a look also in this process via  ```strace -p <PID>```.

--- 

In my case I had to change 

```
    /**
     * @var string Mailadresse die die Lese-Bestätigung empfängt
     */
    public $mailnotify;
```

into 

```
    /**
     * @var string
     *             Mailadresse die die Lese-Bestätigung empfängt
     */
    public $mailnotify;
```

**Comment by kubawerlos** [comment]
please raise a new issue @voku , to provide full issue details
