### ISSUE TITLE
Unable to track down PHP parse error (no filename reported)

### ISSUE THREAD

**Issue by hackel** [FriendsOfPHP/PHP-CS-Fixer#2085]
I'm having trouble figuring out the source of the following error:
```
$ php-cs-fixer fix -vvv
Loaded config from ".php_cs"
PHP Parse error:  syntax error, unexpected '$this' (T_VARIABLE), expecting ';' or '{' in  on line 32
```

I've been using php-cs-fixer on this code for a couple weeks without incident, so this must be caused by a new issue in the code.  I haven't upgraded php-cs-fixer nor altered the configuration.  I've also run my code through `php -l` and phplint just in case, and cannot find any syntax errors.  

I attempted to run this through my debugger (xdebug and PHPStorm), and it caused php to segfault.

I'm running php-cs-fixer 1.11.5 on PHP 7.0.8, Ubuntu 16.04.

My .php_cs:
```php
$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->exclude(__DIR__ . '/app/storage')
    ->in(__DIR__ . '/app');

return Symfony\CS\Config\Config::create()
    ->setUsingCache(true)
    ->level(Symfony\CS\FixerInterface::SYMFONY_LEVEL)
    ->fixers([
        '-blankline_after_open_tag',
        '-concat_without_spaces',
        '-new_with_braces',
        '-phpdoc_short_description',
        '-unalign_double_arrow',
        '-unalign_equals',
        'align_double_arrow',
        'align_equals',
        'concat_with_spaces',
        'multiline_spaces_before_semicolon',
        'ordered_use',
        'phpdoc_order',
        'short_array_syntax',
    ])
    ->finder($finder);
```

**Comment by hackel** [comment]
Update: I started going through all of the files I modified since my last commit and checking line 32, and discovered this was what was causing it to die:
```php
    public function __construct(
        $XML,
        $data_source_id,
        $account_id,
        $order_id,
        $default_company
    )
        //currently will only accept processed data
    {
```
Moving that oddly-placed comment to the top of the method fixed the error and allowed php-cs-fixer to finish.  This syntax is not technically invalid, though it certainly is ugly.

The main issue remains, there is no way to see which file this occurred on.  At some level of verbosity, php-cs-fixer should print the name of each file before it starts parsing it.

**Comment by GrahamCampbell** [comment]
Comment out the code that enables the fast tokenizing linter, and this will should you the file name. @keradus See what I mean about these error messages being terrible, and just make the tool hard to use.

**Comment by SpacePossum** [comment]
```php
<?php

class C {
    public function __construct(
)
    //currently will only accept processed data
    {}
}
```

is valid (https://3v4l.org/eKqqq) but the fixer @ 1.12 with PHP 7.0.4-7ubuntu2.1 (cli) ( NTS ) results in: 
```bash
$ php php-cs-fixer fix test.php --dry-run
You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.
Loaded config from "/home/possum/work/PHP-CS-Fixer/.php_cs".
PHP Parse error:  syntax error, unexpected '}', expecting ';' or '{' in  on line 18
```

```
php -l test.php
```
reports no issues, so something else is off

**Comment by keradus** [comment]
@GrahamCampbell not at all, it's something different.
fast linter is not used here, sa it was merged to 2.x and @hackel is using 1.11.5

**Comment by keradus** [comment]
OK, so, 2 things.

1. You have just discover new bug in BracesFixer. It produces invalid code (the lint error is from already modified code, not from original content of file), so the tool don't want to accept it and override your local file with invalid content, which in general is good. I just created a PR with a bug (thanks for example!), it still needs to be fixed: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2086

2. You have also discover new bug in Fixer (new name: Runner), that in case of crash of atomic fixer (like BracesFixer) it should handle it, but in this case it doesn't. The reason of it was introduced during a bugfix to properly handle semi-reserved keywords and appears only on PHP7. Quick bugfix for it would be this: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2087
Please, could you try it out and confirm it fixes crash of the tool?
The file will be reported as not fixed due to internal errors (because of BracesFixer bug), but the tool won't crash and will still be able to fix all other files.

**Comment by keradus** [comment]
Closing due to merge of #2087
