### ISSUE TITLE
Tokenizing linter doesn't work

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#2153]
The following file is invalid, yet it passes the "fast" linter: https://3v4l.org/ij0AH.

```php
<?php

class Foo
{
    public $bar;
    public $bar;
}
```

See how no exception is thrown: https://3v4l.org/UIF8C.

**Comment by GrahamCampbell** [comment]
Not much use for syntax checking files. :/

**Comment by keradus** [comment]
I would say it works fine for CS usage.
What's the issue with this file to be CS fixed ?

**Comment by GrahamCampbell** [comment]
The issue is one of our fixers could break a file and we'd never know because the new linter passes, but the old one fails. I don't know how many other cases this is true for as well. This is just one I noticed.

**Comment by keradus** [comment]
So let say the initial file is:
```php
<?php class Foo{public $bar; public $bar;}
```

and we would fix it to:

```php
<?php

class Foo
{
    public $bar;
    public $bar;
}

```

Both file passes tokenizer-based linter, but cannot be executed.
File was not damaged by our fixer. 

In general, I **do** agree with you that it would be great if tokenizer-based linter would fail in the first place, but sadly, it didn't. Great to have it in mind and observe, but there is not much we could do except forcing process-based linter, for which I'm against.

1. Why we introduced linting before fixing?
Because a lot of our fixers assume proper token sequence, and then for file with invalid syntax they tries to do invalid operation, and crash for that. To not let that happen we lint the file before fixing it.

2. Why we introduced linting after fixing?
Because sometimes our fixers may introduce not-wanted change. That bad change may lead to file with invalid syntax. Linting after fixing is aiming us to prevent saving that not-wanted changes.
But that changes, which break syntax are an edge case, there may be other changes that will make file somehow not-nicely changed. Some of that changes we do on purpose, but warn users to be extra careful using that fixers (`risky` fixer, eg `strict`). Above that, there could also be unwanted changes that will change code meaning without our approval (eg fixer that will clean whole tokens collection due to some bug) - linter would pass that "new" file, but change wasn't nice.

Linter is not ultimate decision maker if the change is good or no. If it detects violations in syntax after fixing - for sure we did sth wrong and we shouldn't save it. But if it doesn't detect a violation there may still be some not-willing change introduced into code behaviour. For that we have +100k tests.

I'm ready to live with that edge case in mind, at least until somebody will show a real case when we break a syntax in file that was not broken before but tokenizer-based linter pass it.

**Comment by GrahamCampbell** [comment]
Ok, here's a major issue for you then:

```
<?php

return [

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
        ]
        //,

        'redis' => [],
    ],
];
```

Passes the tokenization, but is clearly invalid syntax.

**Comment by GrahamCampbell** [comment]
As you can see here, PHP-CS-FIXER broke the file:

![image](https://cloud.githubusercontent.com/assets/2829600/17851763/a0b84ca4-685b-11e6-8f8a-d2c6a23fdc8b.png)

**Comment by keradus** [comment]
```
D:\GIT\fork\PHP-CS-Fixer (master)
λ php --version
PHP 7.0.10 (cli) (built: Aug 18 2016 10:03:00) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

-------------------------

```
D:\GIT\fork\PHP-CS-Fixer (master)
λ cat test-1.php
<?php

$code = "<?php

return [

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
        ]
        //,

        'redis' => [],
    ],
];";

try {
    var_dump(token_get_all($code, TOKEN_PARSE));
} catch (ParseError $e) {
    var_dump($e);
}
D:\GIT\fork\PHP-CS-Fixer (master)
λ php -f test-1.php
object(ParseError)#1 (7) {
  ["message":protected]=>
  string(78) "syntax error, unexpected ''redis'' (T_CONSTANT_ENCAPSED_STRING), expecting ']'"
  ["string":"Error":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(0) ""
  ["line":protected]=>
  int(12)
  ["trace":"Error":private]=>
  array(1) {
    [0]=>
    array(4) {
      ["file"]=>
      string(35) "D:\GIT\fork\PHP-CS-Fixer\test-1.php"
      ["line"]=>
      int(19)
      ["function"]=>
      string(13) "token_get_all"
      ["args"]=>
      array(2) {
        [0]=>
        string(165) "<?php

return [

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
        ]
        //,

        'redis' => [],
    ],
];"
        [1]=>
        int(1)
      }
    }
  }
  ["previous":"Error":private]=>
  NULL
}
```

-------------------------

```
D:\GIT\fork\PHP-CS-Fixer (master)
λ cat test-2.php
<?php

return [

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
        ]
        //,

        'redis' => [],
    ],
];

D:\GIT\fork\PHP-CS-Fixer (master)
λ php php-cs-fixer fix test-2.php --dry-run --diff --rules=strict_comparison
Loaded config from "D:\GIT\fork\PHP-CS-Fixer\.php_cs.dist".

Checked all files in 0.079 seconds, 4.000 MB memory used

Files that were not fixed due to errors reported during linting before fixing:
   1) D:\GIT\fork\PHP-CS-Fixer\test-2.php
```

**Comment by keradus** [comment]
Sadly, closing as cannot duplicate and lack of reporter involvement :(
