### ISSUE TITLE
[RFC] var_dump/dump fixer

### ISSUE THREAD

**Issue by akovalyov** [FriendsOfPHP/PHP-CS-Fixer#2195]
This RFC is for var_dump/dump removal fixer. While a lot of devs debug via var_dump(or via  Symfony/VarDumper dump), it is dangerous to have it in code, especially if it appears in production . So, why not to introduce these functions removal? What do you think?

**Comment by SpacePossum** [comment]
Hi and thanks for your suggestion :)

How about `var_export` or the `CURLOPT_VERBOSE` flag?
The thing is that we would not be fixing code style, but modifying the way some code works. This is not always a bad thing IMO. However in this case we cannot determine if the `var_dump` is indeed a forgotten debug statement (and the function is not overloaded) or is part of the logic that is essential to the application. 
Therefor I would not add it to the core of the application because it is out of scope and risky. However such a fixer is relatively easy to write and can exists as a custom fixer for your needs.
But lets see what the community thinks :)

**Comment by akovalyov** [comment]
@SpacePossum thank you for your feedback.

 I agree with you that such a functionality might be out of scope of the project. 

Right now I can't judge what is more risky for developer - keeping statements in the code, which are commonly used for debugging, or use the fixer as such. 

However, I think that contrib fixers are usually enabled explicitly by developer, which means that one understands all the consequences of it. 

Anyway, the reason why I've created the issue is that I've already done this fixer for private purposes. If community wants to have that, I will be more than happy to contribute to an awesome tool. If there is no need/it is our of scope of the project, I will just use my fork.

**Comment by buffcode** [comment]
Also consider that those debug statements, especially `var_export($var, true)` could be used to save debug data / traces in production whenever an unexpected error occurs.

**Comment by akovalyov** [comment]
Short summary from PR discussion - too risky to have it in core. For those, who want to have that - https://github.com/akovalyov/DebugStatementsFixers.
