### ISSUE TITLE
Add length_ordered_imports rule

### ISSUE THREAD

**Issue by caiquecastro** [FriendsOfPHP/PHP-CS-Fixer#2374]
Is there any planning to add the length_ordered_imports to the set of rules? As in style-ci?

**Comment by SpacePossum** [comment]
please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2280

**Comment by keradus** [comment]
Closing.
PR is there, waiting for final review
styleCI just provide PHP CS Fixer under the hood, in your case the difference is that they merged the PR to their local fork faster, and we slower. for us it's better to wait a bit longer and have more stable, easier to maintain code.

**Comment by GrahamCampbell** [comment]
This fixer already exists in a pull request: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2280.

StyleCI just uses that fixer. StyleCI's fixer names do not match up with php-cs-fixer completely. The `length_ordered_imports`fixer is actually just a virtual fixer that enables the `opered_imports` fixer behind the scenes.

![image](https://cloud.githubusercontent.com/assets/2829600/21051655/4673f9dc-be19-11e6-819d-cc9fd73138db.png)

The real `opered_imports` fixer is hidden from view, and can only be enabled through the two "conflicting" "virtual" fixers `alpha_opered_imports` and `length_opered_imports`.

We do plan to expose a php-cs-fixer config generator soon, since we're now very nearly totally in sync with php-cs-fixer in terms of fixers.

**Comment by caiquecastro** [comment]
Thanks @GrahamCampbell
