### ISSUE TITLE
can‘t fix i++

### ISSUE THREAD

**Issue by Wuzjaa** [FriendsOfPHP/PHP-CS-Fixer#2432]
use rules $PSR2 @Symfony to fix php code,'i++' will become ++i

**Comment by SpacePossum** [comment]
Hi,
To do this please use the rule `pre_increment`, it is on by default for the SF set.
Note that the fixer will only fix cases where it can be done safely.

If this doesn't work for you please provide:
- valid PHP code you expect to be changed (smallest example possible)
- the version of PHP you are using
- the version of the fixer you are using 
- the configuration you use

We need this in order to help you further.

**Comment by SpacePossum** [comment]
ping @Wuzjaa

**Comment by keradus** [comment]
question is not in valid syntax, creator is not responding. closing.

feel free to discuss if still needed
