### ISSUE TITLE
spell checker

### ISSUE THREAD

**Issue by blendsdk** [FriendsOfPHP/PHP-CS-Fixer#2469]
Hi,

Is it possible to have spell checker in the phpcs which helps fixing typos and spelling in the comments?

Thanks.

**Comment by keradus** [comment]
theoretically it is. please propose a PR

**Comment by julienfalque** [comment]
Isn't is out of scope? I mean, typos are not really coding style issues, are they?

**Comment by keradus** [comment]
Typos in docblocks could be fixed.
We already fix simple grammar issues there.

**Comment by blendsdk** [comment]
I can help implement this if one of the main devs here is willing to provide me a short coaching track.

**Comment by keradus** [comment]
Maybe take a look at https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/COOKBOOK-FIXERS.md ? It could not contain everything, but it should provide you a head start

**Comment by blendsdk** [comment]
thanks

**Comment by SpacePossum** [comment]
@blendsdk any plans on this ? :)
I'm happy to coach a PR if you can share you ideas on how to proceed on this (like what sources/mechanics could be used for spell checks etc.), lemme know!

**Comment by mdwheele** [comment]
@SpacePossum is this still something you're interested in pursuing? I stumbled across this issue looking for another fixer before sending a PR and it piqued my interest, haha.

There are *soooo many* ways a spell-check fix could go wrong, but I think it's actually doable with some work and attention to detail... which seems to be the case for just about every check it seems :grin:. I put together a simple proof of concept that uses `hunspell`:

```
Input
=====================

    /**
     * Hello, wurld. I am a commnet wtih bad spehling.
     * I am heer to maek freinds!
     * 
     * @method SomethingAwful
     */

Output
=====================

    /**
     * Hello, world. I am a comment with bad spelling.
     * I am here to make friends!
     * 
     * @method Something Awful
     */
```

This isn't a Fixer. I was just toying around to see how it would handle auto-corrections out of the box with no adjustment to the dictionary.

The Fixer would be responsible for auto-correction and would delegate down to a `SpellCheck\Source` to `#check` spelling and grab `#suggests`. It would use the best suggestion for each word to do replacements. 

`Source` is an abstraction that could be implemented several ways:
- `ext-pspell` should probably be the first place to look (if installed)
- `hunspell` is installed on RHEL / CentOS 7
- `aspell` is installed on Ubuntu 16.04 / 17.10

We could set a priority of implementations we preferred. If no preferred backend is found, we would need to specify intended behaviour. 

Rather than track which software is on which distributions, we could execute...

```bash
$ which hunspell aspell ispell
/usr/bin/hunspell
/usr/bin/aspell
/usr/bin/ispell
```

...and grab the first one that matches. Use that information to create a `Source` implementation that knows how to use that binary (I've done that with `hunspell`. That's where the demonstration above comes from).

One substantial wrinkle among many: How would you handle when auto-correct gets it wrong? Adding to the dictionary helps in some cases (pointing towards config option), but there are other times where you really do mean one thing and the suggestions are too close together. Perhaps this is an edge case worth only really considering after a more substantial effort has been made.

What do you think about the above ideas? If positive, is it common to have Fixers with injected dependencies that carry some of the workload? Or would it be better to have each fix self-contained?

**Comment by keradus** [comment]
That's the beauty of having spell-checker on Tokens level than generic one.
Fixer would understand the code. And it's context. It could be tighten to only touch comments, and only some part of docblocks. Like it shall not touch your `@method` annotation.

hunspell has no clue about syntax of given programming language.

**Comment by SpacePossum** [comment]
>is this still something you're interested in pursuing?

I would welcome the feature very much. As @keradus stated the fixer could be made to only touch comments and parts of PHPDocs to make it save.
Would the integration with `hunspell` be OK for you @keradus , I've no experience with spelling checkers(API's) TBH.

**Comment by mdwheele** [comment]
> Would the integration with hunspell be OK for you @keradus ? I've no experience with spelling checkers(API's) TBH.

I'd be willing to send support for all of them. In reality, the interface for them is almost identical because they are basically historic progressions on one another.

The detail here is "where do I do that work?". For example, let's say a package *did* exist for working with `hunspell`:

**Should all of the integration be in-lined with no additional external dependencies?** If we're okay with additional dependencies...

**How would that dependency be realized?**

It's not a requirement for php-cs-fixer to function, normally (only if you used the check). Would that mean it goes to `suggest` in `composer.json`?

**How would it be injected (if at all) into the Fixer?**

If I could get some direction there, I think I have enough to get started.

**Comment by keradus** [comment]
> I'd be willing to send support for all of them because it does depend on what's installed.

what about php dependency instead of system one ?

**Comment by mdwheele** [comment]
> what about php dependency instead of system one ?

I looked around for an existing pure-PHP spellcheck implementation and couldn't find anything as performant as `hunspell`, `aspell` or `ispell`. There IS a PHP extension called [`pspell`](http://php.net/manual/en/book.pspell.php) that we could rely on (solving having to pull in a Composer dependency). 

Depending on how this issue went, I was planning on creating a PHP binding for `hunspell`, `aspell` and `ispell` which would auto-detect which was available and use. If `ext-pspell` was available, it would use that before checking what's installed on the system (if anything).

Is that what you mean by "php dependency"?

**Comment by mdwheele** [comment]
FWIW, these utilities are fairly ubiquitous on many Linux distributions.

**Comment by keradus** [comment]
> Is that what you mean by "php dependency"?

no, by php dependency I meant real library written in PHP to solve that issue, not a wrapper that would proxy a call to system.

> FWIW, these utilities are fairly ubiquitous on many Linux distributions.

we support not only linux, but also mac or even windows.

**Comment by mdwheele** [comment]
> no, by php dependency I meant real library written in PHP to solve that issue, not a wrapper that would proxy a call to system.

I could look into that. It would certainly solve the portability issue. It's a complex problem (not so much the algorithm, but the localization of dictionaries). 

So let's say I create `mdwheele/php-spellcheck`, what would the next few steps look like as far as getting it to the fixer? Should I need to inject it? Can I just instantiate inside and treat the FixerTests as black-box?

> we support not only linux, but also mac or even windows.

Because of the complexity of spell-checking, I wouldn't rule out calling down to the system, but I see the concern. These utilities exist on Linux, Mac and even Windows (colored me surprised).

**Comment by keradus** [comment]
:-1: for using custom, own solution. thing is that maintaining of it would be a hell, while using external (php) dep get that cost out

**Comment by SpacePossum** [comment]
I don't think there is a pure PHP external lib out there to help with this.
While we do support multiple OS'es and such, would a wrapper with proper interfacing to configurable tooling work? Bug reports on the used libs. would've to be forwarded to the lib, but that is not different than for the other depends. we got now?

**Comment by julienfalque** [comment]
Closing as the discussion staled.
