### ISSUE TITLE
BracesFixer - removes whitespace inside declare statement

### ISSUE THREAD

**Issue by jeroenvdgulik** [FriendsOfPHP/PHP-CS-Fixer#2476]
The rule 'declare_equal_normalize' is part of the Symfony Ruleset. While the entire Ruleset is quite useful, this particular Rule is not to our liking. Surprisingly while most of the Rules are configurable, this one is not. There is no way to turn it off.

Could we make it configurable so `declare(strict_types = 1);` won't be affected?

**Comment by localheinz** [comment]
Are you asking to make it configurable to fix with and without spaces around `=`?

**Comment by jeroenvdgulik** [comment]
That would be ideal.

But for now it would be good enough to make the rule configurable just so it ignores the `declare` statement instead of 'normalizing' it.

i.e.

```php
    ->setRules([
        '@Symfony' => true,
        'declare_equal_normalize' => false,
        ]);
```

**Comment by SpacePossum** [comment]
@jeroenvdgulik the sample config you provided should switch off the rule, are you reporting this doens't work?

**Comment by jeroenvdgulik** [comment]
>  while most of the Rules are configurable, this one is not.

**Comment by SpacePossum** [comment]
All rules can be switched off, I don't understand.
Can you provide the command you use (please add `-vvv`) and the output and configuration file?

(please confirm the tool loads the configuration you use to switch off the rule, it is on the 1st or second line of the output)

**Comment by jeroenvdgulik** [comment]
What is there not to understand? You _cant_ turn of this Rule if you use the Symfony Ruleset.

**Comment by SpacePossum** [comment]
>What is there not to understand? You cant turn off this Rule if you use the Symfony Ruleset.

Well that is what cannot understand, because you can.
So if you repeat what you are doing but add `-vvv` to the command as I [requested](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2476#issuecomment-275111549) you will see in the output:

```
$ php php-cs-fixer fix test3.php -vvv 
You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.
Loaded config default from "/home/possum/work/PHP-CS-Fixer/.php_cs.dist".
F
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
   1) test3.php (braces)
```

so the Rule `declare_equal_normalize` does not do the change since it configured off, but the Rule `braces`.

**Comment by jeroenvdgulik** [comment]
Ok so the `braces` Rule changes the whitespace? That's pretty... interesting.

So how do stop the `braces` Rule from doing that without messing up my 'normal' braces Rule?

**Comment by SpacePossum** [comment]
ATM you cannot do this, the problem is here:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.0/src/Fixer/Basic/BracesFixer.php#L644
(so if you run the fixer from code you can comment that line out for now)

Please update the title of this report to:
BracesFixer - removes whitespace inside declare statement

Than we ask @keradus kindly to tag it as a bug and if no one has time to work on this ticket I hope I can find some time soon :)

Thanks for reporting!

**Comment by jeroenvdgulik** [comment]
Ok thanks for the explenation and the help. I will await any updates, or maybe take a stab at PR-ing it myself when I have some time
