### ISSUE TITLE
class_definition fixer: multiLineImplementsEachSingleLine configuration request

### ISSUE THREAD

**Issue by Strate** [FriendsOfPHP/PHP-CS-Fixer#2540]
This is how `class_definition` fixer wirks with "multiLineExtendsEachSingleLine".
```diff
interface Bar extends
-    Bar, BarBaz, FooBarBaz
+    Bar,
+    BarBaz,
+    FooBarBaz
{}
```
But I need to do exactly the same, but with `implements` list of class definition:
```diff
-class Bar implements Bar, BarBaz, FooBarBaz
+class Bar implements 
+    Bar,
+    BarBaz,
+    FooBarBaz
{}
```
Is it possible right now? Or it is looks like a feature request?

UPD: This is a part of PSR2 (http://www.php-fig.org/psr/psr-2/#extends-and-implements)

**Comment by SpacePossum** [comment]
The fixer will do this as implements over multiple lines is part of PSR2. Extends is not therefor we have the config option as an opt-in to fix those.
Your 2nd sample is not fixed as the class def. is one line, which is also valid by PSR2. Currently you cannot configure to make all class defs. with extends and/or implements multi line.

**Comment by SpacePossum** [comment]
@Strate let me know if you have more questions after my previous answer. The fixer will make the definition multi line if there is already a line break in it.

**Comment by Strate** [comment]
@SpacePossum but PSR-2 says, that it MAY be done. And, as far I remember, this was possible with csfixer version 1.x. I think it would be great if we could have this option.

**Comment by SpacePossum** [comment]
>but PSR-2 says, that it MAY be done. 

I never said otherwise :)

> And, as far I remember, this was possible with csfixer version 1.x. 

I don' think so

>I think it would be great if we could have this option.

agreed :)

------------------

I think there is some confusion, for example;
```php
interface Bar extends Bar, BarBaz, FooBarBaz
{}
```
Will not be changed either, as it is not about `extends` vs. `implements` as the logic is the same.
The logic the fixer follows is;
if the class/interface/trait extends and/or implements something and at least one of these is not on the same line as class/interface/trait; than make it multi line

As you stated the definition _may_ be over multiple line (and if so must follow another rule), but _may_ also be on one line.
We have never had a way to make all definitions go over multiple lines.
