### ISSUE TITLE
Doctrine annotation indenter incorrectly adds indents after annotations containing other annotations

### ISSUE THREAD

**Issue by edhgoose** [FriendsOfPHP/PHP-CS-Fixer#2681]
The Doctrine annotation indenter behaves unexpectedly for this input, which I've added as a new test in my fork: https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/master...edhgoose:fix-doctrine-annotation-indenter

```
/**
 * @Foo(x={
 * @Bar
 * })
 * @Foo\z
 */
```

I'd expect the `@Bar` to be indented and the rest to be left as is.

This is the output, note `@Bar` is indented correctly but the following annotation `@Foo\z` becomes intended by 4 spaces.

```
/**
 * @Foo(x={
 *     @Bar
 * })
 *     @Foo\z
 */
```

It looks like the annotator doesn't "reset" after closing the `@Bar` annotation.

PHP-CS-Fixer version is master (0a19b49934ad624845b296dc2a584444d6e44787).

PHP version:

```
PHP 7.0.11 (cli) (built: Sep 30 2016 12:31:36) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

I've had a go at fixing it, but I'm struggling to find the cause of the issue. Any assistance would be great and I'll gladly submit a fix.

**Comment by keradus** [comment]
@julienfalque , could you please take care of this report ?

**Comment by localheinz** [comment]
Noticed this one myself, but haven't gotten around to at least providing a failing test case.

**Comment by julienfalque** [comment]
Thanks @edhgoose for taking time fixing this!

Right now I only see one scenario that could lead to this issue:
* on line 4 of your failing case (the line with `* })`): fixer's private method `indentationCanBeFixed()` returns `false` while it should return `true` (the line is part of an annotation, it must be fixed);
* then we don't compute braces delta of this line, which is `-2`, and we don't decrement `$indentLevel` so its value remains `1` (like previous line);
* we don't apply this indentation to this line as it wasn't detected as fixable, but it was already valid so it looks like the fixer correctly "fixed" the line;
* next line is correctly detected as fixable, its braces delta is `0` so indentation level is not changed (still `1`) and we apply it.

So my guess is the bug lies somewhere in `DoctrineAnnotationIndentationFixer::indentationCanBeFixed()`.
