### ISSUE TITLE
php-cs-fixer own config not processed and unable to configure being processed

### ISSUE THREAD

**Issue by glensc** [FriendsOfPHP/PHP-CS-Fixer#2726]
As pointed out in earlier issue (where requested .php extension for config to be supported):
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1027#issuecomment-260180285

the php-cs-fixer own config `.php_cs` is not applied for fixing. and telling in config to do so, has no effect

```
➔ php-cs-fixer.phar --version
PHP CS Fixer 2.3.1 by Fabien Potencier and Dariusz Ruminski (d5257f7)
➔ php --version
PHP 5.6.30 (cli) (built: Mar 10 2017 13:03:30)
```

```php
➔ cat .php_cs
<?php

$header = <<<EOF
For the full copyright and license information,
please see the COPYING and AUTHORS files
that were distributed with this source code.
EOF;

$config = PhpCsFixer\Config::create();
$finder = $config->getFinder()
    ->in(__DIR__)
    ->name('.php_cs');

$rules = [
    'header_comment' => ['header' => $header],
];

return $config
    ->setRules($rules);
```

```
➔ php-cs-fixer.phar fix -vvv
Loaded config default from ".php_cs".
Using cache file ".php_cs.cache".

Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Fixed all files in 0.001 seconds, 9.250 MB memory used
```

expected result would look like this:

```
...
Using cache file ".php_cs.cache".
   1) .php_cs

Fixed all files in 0.100 seconds, 10.000 MB memory used
```

**Comment by keradus** [comment]
ok, so.
1. `Config` class could get any iterable. Then you set it via `setFinder`. If you don't set it on your own and then call `getFinder`, you will have default finder of our project. (Totally cool, just be aware of this).
2. Our default finder ignore hidden files (starting with dots), that's why you don't have that file fixed.

Solution for you?

If you want to use default finder, specif not only name, but also
```php
            ->ignoreDotFiles(false)
```
Other solution would be to not use default finder, but anything that follows iterable.
