### ISSUE TITLE
A blank line is added every time header_comment is updated

### ISSUE THREAD

**Issue by s7b4** [FriendsOfPHP/PHP-CS-Fixer#2730]
Hello all,

Here is the informations :

```
$ php -v
PHP 7.0.18-2 (cli) (built: Apr 19 2017 12:53:19) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-2, Copyright (c) 1999-2017, by Zend Technologies
```

```
$ php-cs-fixer -V
PHP CS Fixer 2.3.1 by Fabien Potencier and Dariusz Ruminski (d5257f7)
```
In my config file, i have

```php
$header = <<<EOF
...
EOF;

$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->exclude('node_modules')
    ->exclude('cache')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setRules(array(
        '@PSR2' => true,
        'header_comment' => array(
            'header' => $header
        ),
    ))->setFinder($finder);

```
If I modify the `$header` variable and run the command `php-cs-fixer fix` again, a blankline is added after the header comment.

```diff
diff --git a/web/index.php b/web/index.php
index 8a9ad5c..ffa17e1 100644
--- a/web/index.php
+++ b/web/index.php
@@ -16,8 +16,10 @@
  *
  * You should have received a copy of the GNU General Public License
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ * New dummy line
  */
 
+
 use \Silex\Application;
 use \Symfony\Component\HttpFoundation\Request;
```

**Comment by keradus** [comment]
Hi!
Thank you for your report. It looks really great and we do have all information what's going on there. I confirm it's a bug.
Sadly, there are a lot of requests currently. Would you like to give it a try and help us via proposing a PR with bugfix ?

**Comment by s7b4** [comment]
Hi,
I will give a try, but i'm not sure to find the problem.

**Comment by keradus** [comment]
That would be really great ;)

First, pick your branch you need to work with.
Since oldest supported version is 2.2, use it as your base branch.

Then, modify `HeaderCommentFixerTest` and add your new case. In this point, PHPUnit/Travis will be failing. This is already very nice help that could be send as PR (it wont be merged before providing fix, but it's a great start if you decided to pass the task for someone else).
Then, try to adjust `HeaderCommentFixer`. Probably it has hardcoded to append new line if fixer is configured to add comment. It shall consider if the comment is already there or not.
If something would not be clear feel free to open w WIP (work in progress) PR and ask inside of it, or just visit our gitter (https://gitter.im/FriendsOfPHP/PHP-CS-Fixer)
