### ISSUE TITLE
Allow for single line IF statements as it is not a PSR requirement

### ISSUE THREAD

**Issue by lukewatts** [FriendsOfPHP/PHP-CS-Fixer#2780]
Allow for single line IF statement as it is not a PSR. 

For example I want to be able to leave this as is:

```
if ($something ) return 'Something';
```
Instead I always end up with:
```
if ($something) {
    return 'Something';
}
```
Maybe I'm nitpicking but this is the only thing I can't seem to override.

I've checked the PSR1/2 specs and they don't explicitly mention this scenario.

The PHP version you are using:
7.0.x

PHP CS Fixer version you are using:
2.3.1

The command you use to run the fixer (and the configuration file you are using if any).
Command:
php-cs-fixer fix --dry-run --diff .

Config file:
[https://gist.github.com/lukewatts/768f06b16dc24b2d5a0652d19243f8c5](https://gist.github.com/lukewatts/768f06b16dc24b2d5a0652d19243f8c5)

A minimal sample of valid PHP code that is not fixed correctly (if applicable).
```
if ($something ) return 'Something';
```

The fixed version of that code after you run the fixer and the version you expected.
I get this:
```
if ($something) {
    return 'Something';
}
```
I'd like this:
```
if ($something) return 'Something';
```

**Comment by julienfalque** [comment]
[PSR-2 does require braces explicitly](http://www.php-fig.org/psr/psr-2/#control-structures):

> The body of each structure MUST be enclosed by braces. This standardizes how the structures look, and reduces the likelihood of introducing errors as new lines get added to the body.

As not using braces in such case is widely considered a bad practice, I would not be in favor of supporting such scenario so I'm closing as _won't fix_.

You could still disable the `braces` rule, although this will disable fixing position and spacing of braces as well.

**Comment by markseu** [comment]
I second @lukewatts, would be good to have a rule that allows single-line statements.

**Comment by andrews05** [comment]
I know this isn't popular, but surely it wouldn't be too difficult to have an option to not create braces while still fixing position and spacing of existing ones? The positioning options currently available already go against PSR-2.
Would you be open to accepting a PR?

**Comment by julienfalque** [comment]
Unfortunately I don't think this is going to happen. Whether the fixer implementation would be trivial does not change the fact that it would add to the maintenance burden once merged.

Note that we don't want to support such rule in this repository but that doesn't mean it cannot be published somehow since the tool allows third party fixers. If you already started working on a fixer, you might still create your own package.

**Comment by roben** [comment]
Sorry for necroing this, but just having a configuration to plainly ignore if statements would be really nice. We are currently (automatically) applying a patch to skip them in the fixer:

```
--- a/vendor/friendsofphp/php-cs-fixer/src/Fixer/ControlStructure/ControlStructureBracesFixer.php 2023-09-11 11:08:29.382855161 +0200
+++ b/vendor/friendsofphp/php-cs-fixer/src/Fixer/ControlStructure/ControlStructureBracesFixer.php 2023-09-11 11:08:26.158898572 +0200
@@ -202,7 +202,7 @@
             T_FINALLY,
             T_FOR,
             T_FOREACH,
-            T_IF,
+            // T_IF,
             T_WHILE,
             T_TRY,
             T_CATCH,
```

**Comment by Wirone** [comment]
@roben Even though we could make this fixer configurable, so you could exclude `if` from the covered control structures, I believe it's not recommended. Non-braced control structures are error-prone, less readable (especially in big chunk of line-to-line code) and that's why all official coding standards, including newest PER-CS v2, enforce curly braces for them.

However, you can create your own rule that would strip curly braces from `if`s, register it in your config and run in your processes. You just need to ensure it's run after `control_structure_braces`.

**Comment by roben** [comment]
Thanks for your insight. Sometimes your hands are tied, though and you have to live with the code style that has been set for you. Also we don't want to strip all curly braces in ifs, we just don't want to enforce it. So stripping them afterwards is not a feasible solution.

**Comment by Wirone** [comment]
In this case you can just copy/paste `control_structure_braces`, modify it to your needs and register as custom fixer (and disable the original one). But personally I would just get rid of patching on-the-fly and apply curly braces. As far as I understand, your code contains both approaches and you just don't want to touch it, but what would happen if you enforced braces? Not that much I believe. Understand your perspective, but we don't have capacity to implement all the edgy cases for people with tied hands 😉.
