### ISSUE TITLE
$$a to ${$a} fixer

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2868]
I don't like var var's, but if used it better be done in the later form to prevent more changes when dereferencing is needed
http://php.net/manual/en/language.variables.variable.php

even more relevant since PHP7 vs.5 diff.;
https://3v4l.org/iMvT9

**Comment by Slamdunk** [comment]
The fixer *must* be different between 5.x and 7.x and the difference should be *very* clear, because they output totally different results. As a completion to your links, note this one:

https://secure.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect

About a year ago I wrote a [PHPUnit extension](https://github.com/Slamdunk/phpunit-extensions/blob/v1.2.0/lib/ClassStandardsTrait.php#L217-L231) (with its [tests](https://github.com/Slamdunk/phpunit-extensions/blob/v1.2.0/tests/ClassStandardsTraitTest.php#L46-L70)) in my project for this, if can be any help.

**Comment by SpacePossum** [comment]
thanks for the pointers @Slamdunk , I did underestimate the issue at hand it seems :|
I'm going to reconsider the feasibility of this fixer.

**Comment by SpacePossum** [comment]
will re-open when I've time
