### ISSUE TITLE
Add an output format that prints the line numbers

### ISSUE THREAD

**Issue by sk-** [FriendsOfPHP/PHP-CS-Fixer#299]
Currently there are only two reporting formats, just the filename and the errors (with verbose mode) and diff, which shows which lines need to be modified.

However, if one wants to modify the file manually it is really time consuming as there are no indications on where on the files these errors are.

Additionally, this feature would be really useful for the integration of this amazing tool and git-lint (https://github.com/sk-/git-lint/). Git-lint is a lint aggregator that shows only errors on modified lines.
Disclaimer: I'm the author of git-lint

**Comment by lukasoppermann** [comment]
@keradus Has this been added? I can't really see lines yet, and this sometimes is a big problem, when in large files you get errors like this. 

```
      --- Original
      +++ New
      @@ @@
           }
      -
       }
```

**Comment by keradus** [comment]
This feature request has never been :+1:'ed and no one has been working on it.
I'm not saying that we won't merge it if it will be made, but there were no interest on it yet except @sk- .

If you want, please start working on that feature and for sure we will help you with your PR ;)

**Comment by lukasoppermann** [comment]
Ahh, I see, well, sorry, I have no idea how to do it. :(

**Comment by sstok** [comment]
#1370

**Comment by Bilge** [comment]
The issue seems to be that fixers themselves do not report the location at which they attempt to modify a file, because they can't, because `FixerInterface` specifies that fixers only receive `Tokens` that do not contain information about lines in a file. Therefore, the only way to know where errors were found is to let the fixer make its changes and run a diff, making a note of the lines in the source file that were changed.

This library currently has diff functionality (but is only invoked when the `--diff` option is specified). However, it uses [sebastianbergmann/diff](https://github.com/sebastianbergmann/diff) which is a crude unified diff implementation; so crude it [does not include any information about the range of lines affected](https://github.com/sebastianbergmann/diff/blob/7a31372a53d0c52bb2d4e95cf600338735fb4a36/src/Differ.php#L101) as in a [normal unified diff](https://en.wikipedia.org/wiki/Diff_utility#Unified_format).

A fork of bergmann's diff library called [nochso/diff](https://github.com/nochso/diff) addresses this issue by adding line numbers, however it is not maintained and has no tags, so we'd have to rely on `dev-master`. Furthermore, the library outputs an array of `DiffLine` objects containing the line number which would be handy to use directly, however this library's `DifferInterface` specifies that diffs must return a `string`, which means the array of `DiffLine`s would have to be converted to a string and then reparsed, which is obviously grossly and unnecessarily inefficient.

Without a reliable PHP diff implementation it does not seem possible to proceed with a solution at present, unless someone were to undertake the challenge of including line numbers in `Token`, which would be the most efficient implementation since we already know which tokens were changed; just not which line they pertain to.

**Comment by rayfoss** [comment]
I was looking for something of this sort, but it doesn't seem to exist, and was hard to pull off :/ 
<img width="942" alt="reporter_problems" src="https://cloud.githubusercontent.com/assets/876076/26690168/ee136e0c-46bd-11e7-9759-498ad6f34a74.png">

**Comment by SpacePossum** [comment]
We will start providing line numbers based on the diff package of Sebastian Bergmann.
As such I opened https://github.com/sebastianbergmann/diff/pull/45 which I hope make its way to the next 2.0 release of the package. This is a process of time (like the diff v.2 package will require PHP 7 while here we support 5.6 as well) so please hang on :) 

Alternatively we're open for ideas and PR's on this topic, however I would highly recommend discussing possible solutions before putting a lot of time and/or effort in a PR.

**Comment by SpacePossum** [comment]
closed by the merge of https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3162
