### ISSUE TITLE
Scalar types should be added to PHP keywords

### ISSUE THREAD

**Issue by Jean85** [FriendsOfPHP/PHP-CS-Fixer#3049]
I was having trouble understanding why the fixer for lowercasing keywords was not working on this piece of code:

    public function test(String $string)

From PHP 7+, we now have scalar types (int, string, float, bool), but `Token::getKeywords()` doesn't fetch them as keywords. Should we import them as such so related fixers can work on them?

**Comment by SpacePossum** [comment]
Thanks, this is indeed lacking. When resolving it might be worth looking at `void` as well for PHP7.2 as return type hint. I spotted the last case but didn't work on it.
Would like to see this supported, so if you've the time, please give it a try! :)

**Comment by hamdrew** [comment]
#4126 (native_function_type_declaration_casing rule) should handle PHP's reserved words for native types, at least within function definitions.  The only other place they should be used is through casting, and those are already a part of the `T_*` parsing token constants.  

Both PHP and PHP-CS-Fixer distinguish between [keywords](https://www.php.net/manual/en/reserved.keywords.php) (those with `T_*` constants) and [other reserved words](https://www.php.net/manual/en/reserved.other-reserved-words.php). PHP limits their uses differently, and PHP-CS-Fixer has very different code to handle the two sets of words.

Because the "lowercase_keywords" rule explicitly mentions keywords, and not reserved words, I do not believe that this rule should be updated to handle the case you mention. I think you could consider this issue closed, as there is a rule available to cover it. 

There is an open issue (#4502) to support [PSR-12](https://www.php-fig.org/psr/psr-12/), which should cover both of these cases.

Apologies for the thread necro, I have been perusing "easy picks" to learn more about the project and help contribute.

**Comment by SpacePossum** [comment]
This has been added in v2.15.0 as `native_function_type_declaration_casing`

Tests for it can been seen here:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.15.0/tests/Fixer/Casing/NativeFunctionTypeDeclarationCasingFixerTest.php#L137
