### ISSUE TITLE
Yoda-style is inconsistent when using comparison operators

### ISSUE THREAD

**Issue by nicolas-grekas** [FriendsOfPHP/PHP-CS-Fixer#3075]
I just spotted that `count($groups) === 0`
is turned into `0 === count($groups)` when yoda style is enabled,
but `count($groups) > 0` is left unchanged,
whereas I would have expected `0 < count($groups)`.
That's a very minor issue so if it's not worth it to you, feel free to close :)

**Comment by SpacePossum** [comment]
I left it in the `don't care so "null"` for SF the project (and default `SF ruleset` ) because of some discussion where people stated that Yoda is to prevent accidental assigned and that is never the case with `<` for example.

However, I did throw in an option. So from the docs:
```
yoda_style [@Symfony]

Write conditions in Yoda style or not based on configuration.

Configuration options:

equal (bool, null): change equal (==, !=) statements; defaults to true
identical (bool, null): change identical (===, !==) statements; defaults to true
less_and_greater (bool, null): change less and greater than (<, <=, >, >=) statements; defaults to null
```

key here is the `less_and_greater` option. 
So if you this changed, feel free to update the configuration of your project :)
Or if you are sure this is what should be the case for all SF projects we could adjust the `SF ruleset`.

**Comment by SpacePossum** [comment]
Closing as I think this one is answered, i.e. the inconsistency can be resolved using different configuration.
Please @nicolas-grekas let me know if I missed something.
