### ISSUE TITLE
Getting yoda fixes even though I disabled that option

### ISSUE THREAD

**Issue by mnapoli** [FriendsOfPHP/PHP-CS-Fixer#3398]
#### The PHP version you are using (`$ php -v`):
=> 7.2.0

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> `PHP CS Fixer 2.9.0 Speechless by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
=> `vendor/bin/php-cs-fixer fix --dry-run --diff --allow-risky yes`

#### The configuration file you are using, if any:

=> https://github.com/PHP-DI/PHP-DI/blob/323f76ec2aa70cb367d54f7dc9c1a5fe403a16a4/.php_cs#L21-L23

Extract:

```php
        'is_null' => [
            'use_yoda_style' => false,
        ],
```

#### Diff generated

```php
@@ @@
         $errorMessage = $this->isCompilable($value);
-        if ($errorMessage !== true) {
+        if (true !== $errorMessage) {
@@ @@
```

Expected: no changes.

The `if` should not be flipped since I disabled yoda conditions. I don't understand why php-cs-fixer changed its behavior, I did not change that code and I did not change the configuration.

**Comment by keradus** [comment]
you have configured `is_null` fixer to use or not the yoda style, as `is_null($foo)` may change it to `null === $foo` or `$foo === null`, you have configuration for it. And that's it.
Presented code was not touched by `is_null` fixer, as there is no `is_null` invocation !
You are using `yoda_style` rule, configure it.

**Comment by mnapoli** [comment]
I don't understand, this was not applying before. I maintain something has changed or there is a bug. FYI I am *not* using the `yoda_style`, it is not in my config file as you can see in the link, I've never used it and php-cs-fixer never offered to change my conditions before.

Anyway thanks.

**Comment by mnapoli** [comment]
Well I was not crazy, I'm now getting this error on my CI:

>   [PhpCsFixer\ConfigurationException\InvalidConfigurationException]  
>   The rules contain unknown fixers (yoda_style).

This fix was not here before.

**Comment by kubawerlos** [comment]
Travis has a job with`--prefer-lowest` and you have `"friendsofphp/php-cs-fixer": "^2.4"` as dependency in `composer.json` - `yoda_style` fixer was introduced in PHP CS Fixer 2.6, so you have to update `composer.json`.

**Comment by julienfalque** [comment]
Also when `yoda_style` was introduced it was added to the `@Symfony` ruleset, which means you _are_ using it.

**Comment by mnapoli** [comment]
@julienfalque So to sum up, we should not use the `@Symfony` ruleset if we want to have backward compatibility? Does the same apply to the default rules or are those defaults always backward compatible?

@kubawerlos I'm running php-cs-fixer outside of Travis, but yes you are right that CI was using a different version, that explains it (though I'd still want to get the same result regardless of the version if I don't change the code or the config).

Thanks for your answers!

**Comment by julienfalque** [comment]
@mnapoli Rulesets should not be seen as totally frozen arrays but as sets of rules that match a specific codestyle/specification/purpose, including the rules that are not implemented in PHP CS Fixer _yet_. 

`yoda_style` was implemented recently but Symfony followed that rule for a while, so it was added to the set because it was missing. The same applies to `no_break_comment` which was added to the `@PSR2` ruleset a few months ago.

If you use the `@Symfony` ruleset but don't want to use `yoda_style`, then you actually don't fully follow Symfony codestyle; if you use the `@PSR2` ruleset but don't want to use `no_break_comment` then you don't fully comply with PSR-2. It makes sense to me that _you_ need to be explicit about that.

Though I agree having new unwanted rules enabled when upgrading PHP CS Fixer can be undesirable. You might want to see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1112.

**Comment by mnapoli** [comment]
Thanks that makes sense indeed, and thanks for the link to #1112 that sounds like a very good idea!
