### ISSUE TITLE
Disable phpdoc_align?

### ISSUE THREAD

**Issue by zored** [FriendsOfPHP/PHP-CS-Fixer#3450]
I there any way to **disable** vertical align for phpDocs?

Before and after:
```php
    /**
     * @param            $jobClass
     * @group             functional
     * @dataProvider dataJobCreation
     */
```
What I expect:
```php
    /**
     * @param $jobClass
     * @group functional
     * @dataProvider dataJobCreation
     */
```
Config field: `'phpdoc_align' => false` or `'phpdoc_align' => ['tags' => []]` (some other field?).
Command: `php-cs-fixer fix --config=.php_cs foo/Bar.php`.
CS Fixer `2.10.0`.
PHP `7.1.13`.

**Comment by SpacePossum** [comment]
Hi,
AFAIK we have fixers to align PHPDoc tags, but not one to unalign these.
It would be nice to have a fixer (or configuration of an existing one) for it though :+1:

**Comment by zored** [comment]
PR is now available 👍

**Comment by zored** [comment]
Any blockers for releasing this feature? :(

**Comment by keradus** [comment]
Let us discuss blockers on the PR itself ;) I just took a quick look and raised some comments.

Sorry for asking to to wait so long.
Sadly, project is not so little anymore.
In moment of writing this comment there are 142 issues and 57 PRs.
Time needed to properly analyse all raised issues and review+verify PRs is huge for our core team.
That's why we cannot do everything we would like to as fast as we would like to :(

Once again, thank you for your great improvement idea and PR for it, we do appreciate it!

Friendly note, as I stated on our gitter channel, I'm offline for a week since tomorrow.
