### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by musayazlik** [FriendsOfPHP/PHP-CS-Fixer#3678]
https://resmim.net/f/uJs1cO.png

I have a problem with the above link in my Atom.io editor. How can I solve this problem?

**Comment by keradus** [comment]
to install, follow one of proposed ways:
https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation

probably atom editor has not install PHP CS Fixer.
(note: `atom-beautify` plugin you are using is userland plugin, nothing official from our side(

**Comment by musayazlik** [comment]
I installed the plugin, but it did not improve.

**Comment by keradus** [comment]
the error you post originally was already from this plugin, so you got it before as well.
what is error saying is that instead of only installing the plugin, you need to install PHP CS Fixer as a standalone, globally installed tool.
They provide you a link with some instructions in error message, or simply use official instructions I linked for you ;)
