### ISSUE TITLE
NoUnusedImportsFixer: Naive search doesn't remove all unused imports

### ISSUE THREAD

**Issue by jnvsor** [FriendsOfPHP/PHP-CS-Fixer#3743]
#### The PHP version you are using (`$ php -v`):  
`7.2.4-1`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):  
`2.11.1 Grey Devil`

#### The command you use to run PHP CS Fixer:  
`./vendor/bin/php-cs-fixer fix t`

#### The configuration file you are using, if any:
```php
=> ....................................
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

use Woot\Test\This\Thing;

// This isn't even a doc comment never mind a @param or something...
// Why does php-cs-fixer not remove the use statement just because
// there's a single instance of the word 'thing' in this file?
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

use Woot\Test\This\Thing;

// This isn't even a doc comment never mind a @param or something...
// Why does php-cs-fixer not remove the use statement just because
// there's a single instance of the word 'thing' in this file?
```

 * with the changes you expected instead:
```php
<?php

// This isn't even a doc comment never mind a @param or something...
// Why does php-cs-fixer not remove the use statement just because
// there's a single instance of the word 'thing' in this file?
```

**Comment by ntzm** [comment]
This hopefully should be dealt with in #3668 + #3445

**Comment by julienfalque** [comment]
Actually this is not covered by #3445 as references in comments are still taken into account, even if the check is a bit more precise. This behavior is intentional and thus must remain the default until next major version.

See #2814 for a discussion regarding options that we want to add to allow tweaking comments handling. As we already have an issue to track that, I'm closing this one as duplicate, thanks :)
