### ISSUE TITLE
Document life-cycle of fixers

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#3795]
For Fixers there is a life-cycle to consider.

For our fixers and 3rd party:
The following methods _must_ be idempotent:
- `isRisky`
- `getName`
- `getPriority`
- `getDefinition` if `DefinedFixerInterface` is implemented
- `getConfigurationDefinition` if `ConfigurationDefinitionFixerInterface` is implemented
- `getSuccessorsNames` if `DeprecatedFixerInterface` is implemented

This can only be documented.

The following methods  _must_ be called first: 
- `configure` if `ConfigurableFixerInterface` is implemented
- `setWhitespacesConfig` if `WhitespacesAwareFixerInterface` is implemented

, before using the following methods:
- `fix`
- `isCandidate`
- `supports`

Currently we only check (in the `AbstractFixer`) that `configure` is called before `fix` when applicable, I suggest for check the others as well.

**Comment by keradus** [comment]
:+1: for idea

-------------

> configure if ConfigurableFixerInterface is implemented

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.11/src/AbstractFixer.php#L57

> setWhitespacesConfig if WhitespacesAwareFixerInterface is implemented

`setWhitespacesConfig` is called in `FixerFactory`, it has to be called from outside of `Fixer` (as Fixer don't know what user wants to use), but even if it would not be called at all, default config is there:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.11/src/AbstractFixer.php#L64

so, they are both called before `->fix`, which is crucial indeed.



`isCandidate` was our idea how to boost single fixer performance.
but actually, from time perspective, this method is not needed at all for `FixerInterface`.
Why? because even if one would implement `FixerInterface::isCandidate`, he doesn't need to call it! And we, internally, when using the `AbstractFixer`, are calling it indeed, but that abstract parent class is... internal. 

Similar to `::supports`.

Question is - do we want to have dualism in how we are handling those two "helping" methods, as currently we do it like that:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.11/src/Runner/Runner.php#L181 .


The issue for `configure`+`setWhitespacesConfig` vs `fix`+`isCandidate`+`supports` has to be discussed in 3 cases:
- our internal fixer, our runner
- external, custom fixer, our runner
- external, custom fixer and external, custom runner

One of the solutions would be:
- drop `FixerInterface::isCandidate`+`FixerInterface::supports` and keep only `FixerInterface::fix`,
- create public `AbstractFixer` class that exposes `final fix(...)` method as template method pattern and exposes `abstract isCandidate`+`abstract supports`

**Comment by SpacePossum** [comment]
Closing as this is better a part of the doc refactor and whatever changes version 3 is going to bring (if any) on this topic.
