### ISSUE TITLE
 Add ImplodeCallFixer

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#3904]
Function `implode` can be called in 3 ways, one - not [documented](http://php.net/manual/en/function.implode.php) - which should be fixed:
```diff
 <?php
-implode($pieces , '');
+implode("", $pieces );
```

and two that are correct:
```
<?php
implode("", $pieces);
implode($pieces);
```

How should we handle these 2 signatures? I could not find any conclusive reason one is better than the other - should the fixer have an option `empty_string` with values `ensure` and `remove`? If so what would be the default (and why?) and would that default be our default here?

Or maybe one signature is somehow better and should be recommended?

**Comment by SpacePossum** [comment]
:+1:  for fixing to `implode("", $pieces);` , as it is more explicit and used in same way as the counter part `explode`

**Comment by gharlan** [comment]
Maybe `implode($pieces , '')` will be deprecated in 7.4:

https://wiki.php.net/rfc/deprecations_php_7_4

> The following are still Work-In-Progress and ideas:
> * Unify parameter order for implode() to match explode()

**Comment by kubawerlos** [comment]
The `implode($pieces , '')` case is obvious how to handle - I'm asking how to approach 2 correct, documented usages.

**Comment by gharlan** [comment]
I agree to @SpacePossum, we should fix it to the explicit one `implode('', $pieces)`.
I would not add a configuration option for it, until it is explicitly demanded by someone who wants to use `implode($pieces)`.

**Comment by gharlan** [comment]
[It](https://github.com/symfony/symfony/blob/3359a46f7c53f372bf919076dfd431b25c6c1c9e/src/Symfony/Component/Intl/Resources/bin/common.php#L64) [seems](https://github.com/symfony/symfony/blob/a5dbc68cd402cf5120f1aac12a78e31809c3312f/src/Symfony/Component/Console/Output/ConsoleSectionOutput.php#L77) [to](https://github.com/symfony/symfony/blob/a5dbc68cd402cf5120f1aac12a78e31809c3312f/src/Symfony/Component/Console/Output/ConsoleSectionOutput.php#L126) [be](https://github.com/symfony/symfony/blob/6781e53f86997634566c0f9cdef597ab1795d231/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php#L121) [symfony](https://github.com/symfony/symfony/blob/a5a91d318ce73256b7c9677c3d46cf989383d006/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateIntervalToArrayTransformer.php#L122) [standard](https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Component/HttpKernel/HttpCache/Ssi.php#L90) to use `implode('', $pieces)` instead of `implode($pieces)`.
