### ISSUE TITLE
Psr4Fixer - option to change filename instead of classname

### ISSUE THREAD

**Issue by enumag** [FriendsOfPHP/PHP-CS-Fixer#4079]
I'd like PHP-CS-Fixer to fix my files according to PSR-4. The problem is that the current fixer does it by changing the classname. In my cases the classnames are correct and it's the filenames that should be fixed instead.

After some searching I found [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/857) old issue where you guys discussed whether the fixer should change classname or filename and decided to not implement it.

But then you [added](https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/927350e9e4e354335d0aecba53a1e509e3b45aef#diff-662857e543a68aca4dae877ffefb4d73) the fixer regardless 2 years later apparently without any discussion about this.

What confuses me even more is that the author of that fixer @GrahamCampbell previously [said](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/857#issuecomment-67349898) it should fix the filename but then implemented it to fix the classname instead.

Did I miss some more discussion about this? Can the support to change filename be added?

**Comment by SpacePossum** [comment]
Hi!

I did some digging and the the PSR4 fixer was added in the same way we add all new features for years; through open discussion here @ GH :)
here is the PR https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1489

Now that PR and its discussion are over 3 years old and a lot has changed since than.
People come and go, new opinions, ideas and roadmaps have been developed and the scope of this tool has been redefined based on user input.

Currently I think having the tool renaming files is out of the scope of what it should do. The main focus is to fix code style up to widely accepted code-style standards. While PSR0 and PSR4 are standards, there are not mainly about code style so it is limited what we can do.

It is however my opinion though and since you already read up on some of it you know you can find other opinions as well :)

**Comment by SpacePossum** [comment]
The main concern for this tool/project is fixing code style to widely accepted standards and where possible do a bit of SCA and fix to better code, therefore I feel renaming file is out of the scope of the tool. As such I'm closing this for now but please continue any discussion on if wanted!

**Comment by TomasVotruba** [comment]
@enumag Still relevant? Should be pretty easy with configurable Rector rule

**Comment by GrahamCampbell** [comment]
Renaming files will not be possible. In particular, because the tool accepts input via stdin. No way to rename that!

**Comment by enumag** [comment]
@TomasVotruba Kinda relevant but... I need it so rarely that it's not really worth it for me to install another tool to do this anyway. Better don't bother with a Rector rule for this or only if you or some other ppl need it.

**Comment by TomasVotruba** [comment]
@GrahamCampbell I talk about @rectorphp, where we rename files to match PSR-4 in various structures.

@enumag Ok, just checking. There are already rules to match PSR-4 paths in `composer.json`, whatever the structure is.
