### ISSUE TITLE
Is "Coding Standards" different from "Code Style"?

### ISSUE THREAD

**Issue by skyvondave** [FriendsOfPHP/PHP-CS-Fixer#4257]
Sorry, this is just a question of clarification: In PHPStorm, there's a "Code Style" editor that lets me configure how code formats, which can be configured to PSR standards, but this repo is named PHP-**CS**-Fixer where CS has the same acronym as Code Style, so I can't tell if it's referring to the same thing or there's some relevant difference.

**Comment by keradus** [comment]
closing as not a real issue, feel free to continue the discussion anyway

Style is more how it looks alike, how code is looking, where it has some spaces and so.
Standards are more than style, they may define the style as well, but not stop of them. eg forcing on you some good practices (using `===` instead of `==`, which is not only looking different, but also work different; using new methods of frameworks (eg PHPUnit) instead of legacy, deprecated ones and so).
With years, different tools are going into a path of somehow touching both.

**Comment by skyvondave** [comment]
I'm not clear if you're saying the repo's "Coding Standard" is different than PHPStorm's "Code Style", or how exactly it is.

**Comment by keradus** [comment]
Nobody will give you clear definition and put hard line between them that everyone would agree with.
Originally, code style was for where you put whitespace, and coding standard also for way of writing the code - like to not use switch/case or crappy methods of given library. With time and evolution of tools, the border is not that clear.

**Comment by skyvondave** [comment]
I think the author or someone familiar enough with the code would be able to say whether "Coding Standards" in the repo acronym was the same as "Code Style" in PHPStorm as JetBrains meant it; I don't think that's an unreasonable expectation.

So if Coding Standards is meant differently by the author as Code Style, then clarification of what those differences are would be very useful.

If your definitions are good enough to understand the differences (or if they simply mean the same thing), then great. I can simply try it and see if it does what it looks like, but I was simply looking for a clarification on the term as it is different and often engineers are very particular in what they mean, or intend that there is a described difference.

**Comment by keradus** [comment]
I'm the author of PHP CS Fixer. And I gave the description already.
If you want clarification of other entities, like mentioned PHPStorm, ask them instead.
