### ISSUE TITLE
php_unit_no_expectation_annotation PHPUnit 7+ Support

### ISSUE THREAD

**Issue by donatj** [FriendsOfPHP/PHP-CS-Fixer#4268]
The syntax generated by `php_unit_no_expectation_annotation` does not currently support PHPUnit 7+

Whereas `->setExpectedException*` works in PHPUnit 6 and earlier, it was actually a deprecated syntax for a while. It was removed in PHPUnit 7. 

PHPUnit 7 now uses:

```php
$this->expectException(\XmlRpc\Exceptions\XmlRpcDecodingException::class);
$this->expectExceptionCode(10);
$this->expectExceptionMessage("Soup");
$this->expectExceptionMessageRegExp("/soup/i");
```

**Comment by keradus** [comment]
Use not only `php_unit_no_expectation_annotation`, but also `php_unit_expectation`, then you would see what you want.
Or better, instead of picking the rules manually, use already prepared for you ruleset: `@PHPUnit60Migration:risky`, which has everything configured.
(the methods were removed in v7, but are available since v6 already, thus 6.0 migration ruleset)

**Comment by keradus** [comment]
Closing as answered and this is more support question than issue report.
If you are willing to, feel free to continue discussion here or on our gitter channel

**Comment by keradus** [comment]
I am closing this issue as it has been answered and it is more a support request than issue report/feature request.
If you are willing to, feel free to continue discussion here or on our [gitter](https://gitter.im/PHP-CS-Fixer/Lobby) channel.
