### ISSUE TITLE
What do you consider a BC break?

### ISSUE THREAD

**Issue by mlocati** [FriendsOfPHP/PHP-CS-Fixer#4323]
`@Symphony` rules changed over time in the 2.x series. If someone uses it, this leads to different results for different php-cs-fixer versions.

Furthermore, most of the classes are marked as `@internal`, IMHO meaning that maintainers are free to break BC even in dot releases.

So, it'd be fine to know what does the maintainers consider a BC break.

**Comment by SpacePossum** [comment]
I think a clear separation between code and rules & sets should be made to answer the question.

For code, we basically follow symfony https://symfony.com/doc/current/contributing/code/bc.html

For the rules and sets however it is a bit different. While we like to provide a complete implementation of a fixer for PSR1, 2, Symfony, etc. we know we don't have everything in place.

So lets say someone makes a new rule for PSR2 and you configured the fixer to fix towards PSR2, than when you update the new fixers gets to work and might change code it did not do before.
This is not consider a BC break because your code is still fixed to PSR2 and that is what you configured.

For the SF set even more changes happen because the standard changes more frequent than lets say a PSR.

If you do not want you code to be fixed to let say PSR2 but only want to apply the rules we currently have for PSR2 you are better of configuring these rules separately as a list and not as the set.
That way, when we add new rules to the set your code is far less likely to be changed after updating the fixer.

You might be interested in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1112
