### ISSUE TITLE
"Skipped" status in progress output is confusing

### ISSUE THREAD

**Issue by teohhanhui** [FriendsOfPHP/PHP-CS-Fixer#4383]
When the file is "skipped" because of the cache, the correct output should be `.` for "no changes", not `S` for "Skipped".

**Comment by teohhanhui** [comment]
Rationale: The user only cares about whether the file is okay, or not. Imagine if phpunit or behat has a cache, and decides to output "Skipped" for cached tests. That would confuse the heck out of everyone.

**Comment by SpacePossum** [comment]
Hi and thanks for the suggestion,

It's always helpful to hear what the end users find confusing and what can be tweaked, especially if you work on a project for a while as you might get blind for the details!

If PHPUnit had a cache and cached the test results I would prefer knowing it through some feedback. As such I think have different indicators for different states isn't that bad, but I agree that we don't explain the _why_ something is skipped.

I made a proposal to clarify the state, let me know what you think :)

**Comment by teohhanhui** [comment]
As a matter of fact, PHPUnit does have a cache now, and it didn't change the progress output, as far as I could tell.

**Comment by kubawerlos** [comment]
@teohhanhui PHPUnit uses the cache only to change the order of tests - it caches the results to be able to run the failed test first in the next run. No tests is skipped because it is cached.

Thinking from a perspective of PHPUnit user who discovers PHP CS Fixer when seeing `S` in progress then might think the file was skipped because it was marked to be skipped (like we can do in PHPUnit) and not because the file was already checked and have no changed since.
