### ISSUE TITLE
No return type fixer

### ISSUE THREAD

**Issue by Bilge** [FriendsOfPHP/PHP-CS-Fixer#4482]
I expected there to be a PHP70 migration fixer to enforce return types for all methods, but there doesn't seem to be one. I understand some types, such union types and `mixed` cannot be expressed directly in PHP, but such a fixer should be smart enough to permit the `@return` annotation in lieu of a return type declaration. In this way, the fixer ensures the developer expressed the return type *somewhere* whereas at the moment it is entirely possible to completely forget a return type and this tool is unable to point out the omission.

**Comment by julienfalque** [comment]
IMO enforcing a return type is out of the scope of PHP CS Fixer. This can be achieved with other tools such as [PHPStan](https://github.com/phpstan/phpstan) with [strict rules extension](https://github.com/phpstan/phpstan-strict-rules).

PHP CS Fixer can help if you want actual type declarations rather than PHPDocs using rules `phpdoc_to_return_type` and `no_superfluous_phpdoc_tags`. See also #4056 for future `phpdoc_to_param_type` implementation.

**Comment by Bilge** [comment]
Maybe that's correct since this is just a check and there isn't really a _fixing_ component to it.

**Comment by keradus** [comment]
While I agree it's nice to always have return type, if it's missing, it's not that much we can put there.
the best we can do for **automated code change** PHP CS Fixer provides is `phpdoc_to_return_type`.
