### ISSUE TITLE
Install composer locally question

### ISSUE THREAD

**Issue by danielspk** [FriendsOfPHP/PHP-CS-Fixer#4496]
Why is the installation not documented by composing the project locally? Are there any problems detected?

**Comment by kubawerlos** [comment]
I have no idea, it's the way I install this library every time :)

**Comment by ktomk** [comment]
@danielspk: If I may ask, what do you exactly mean by composing the project locally? Are you cloning sources from Github and then do composer install or do you mean to require via composer cs-fixer as a dev dependency?

**Comment by danielspk** [comment]
I require via composer cs-fixer as a dev dependency.

It works correctly. It simply catches my attention that it is not documented in the README.md as a valid means of local installation.

**Comment by keradus** [comment]
it's fully possible.
looks like a person who created this part of docs focused on more "fancy" cases leaving the obvious one not documented.
@danielspk , can you extend the documentation to cover that case? thanks !

**Comment by danielspk** [comment]
Ready!

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4560

**Comment by ktomk** [comment]
@danielspk Thanks for the quick feedback and for taking care directly filing a PR.

You asked about if *"there [are] any problems detected?"* when adding PHP-CS-Fixer as a composer dev dependency.

If you make use of PHP-CS-Fixer in a project that also has non-dev dependencies which collide or intersect with PHP-CS-Fixer (e.g. Symfony components), composer needs to find install candidates across all of them. This might lead to upgrade/downgrade of non-dev requirements only due to dev requirements which most often is not wanted (and can also lead to unresolved deps under circumstances).

Apart from that, there aren't any problems that I know of. I use it as dev dependency in some projects, but I think I do not have any same dependencies in these.

To avoid such problems altogether, take a look at the phive installer from phar.io. PHP-CS-Fixer is available via it as well and you can have the tooling independent to your composer requirements. I can highly recommend it: https://phar.io/

**Comment by keradus** [comment]
just to fulfill the picture - issue described above is relevant for any package installed via Composer, not just PHP CS Fixer

**Comment by ktomk** [comment]
Absolutely what @keradus wrote, this is nothing specific to the PHP-CS-Fixer project, this is just how composer works in any composer based project.

IMHO for a self-containing build in a project this is sort of fine, but it comes w/ work if this goes more into tooling. It is also possible to care about that in the build, e.g. use a different vendor directory in the
build tool-chain, a different composer.json and what not. Or just phive. Or what not. ;)

**Comment by SpacePossum** [comment]
I'm closing this after the discussion here and @ the PR https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4560 , I'll also close the PR.

Feel free to keep the discussion going, if in the end there is a majority in the community to this to the documentation than I'm happy to reopen.
