### ISSUE TITLE
PHPUnit dedicated assert 

### ISSUE THREAD

**Issue by kubawerlos** [FriendsOfPHP/PHP-CS-Fixer#5052]
To convert PHPUnit assertions to we have currently 2 fixers:
- `PhpUnitConstructFixer` that converts `assertSame`-ish assertions to `assertFalse`, `assertNull` and `assertTrue`, but not to `assertCount`
- `PhpUnitDedicateAssertFixer` that converts `assertTue` to dedicated assertion and `assertSame` to `assertCount`

Am I missing something or we could have one fixer which does the conversion?

Because I'm not sure where https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4845 would fit.

Pinging @keradus and @SpacePossum as the authors of mentioned fixers.

**Comment by SpacePossum** [comment]
I can't recall why these are 2 rules, maybe to reduce complexity as both fixers have their fair amount of logic.
On feature level I think this could be one `rule` and might also include `php_unit_dedicate_assert_internal_type` and new options to support https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4845

**Comment by keradus** [comment]
- `php_unit_construct` -> use dedicated (assertTrue/False/Null) assertion instead of manual check. we are converting explicit usage of `true/false/null` constant to dedicated assertion method
- `php_unit_dedicate_assert` -> use dedicated assertions instead of `assertTrue`
- `php_unit_dedicate_assert_internal_type` -> use dedicated assertion instead of `assertInternalType`

Each rule is converting different scenario, each rule requires different PHPUnit version.
To be honest, i don't see a need to combine them into single fixer. Is it possible? yes. Myself, i would prefer to keep them atomic and if someone is willing to upgrade his PHPUnit, let her/him use the PHPUnit set and not directly the methods.

If there would be nice code simplification/reduce, i would be OK to have them merged. But if we just merge the classes and have 1 huge file as result, maintainability cost increased for the gain that I struggle to see.

**Comment by keradus** [comment]
#4845 should go into `php_unit_dedicate_assert`, as it would convert `assertTrue` to dedicate assertion.

**Comment by keradus** [comment]
Closing for now, due to reasoning. Feel free to continue the discussion (although not so much discussion was here) and prove that we would have great benefit of combining those rules. But maybe that's not worth the effort
