### ISSUE TITLE
How to add a blank line before each DocBlock

### ISSUE THREAD

**Issue by Aerendir** [FriendsOfPHP/PHP-CS-Fixer#5101]
After running a series of automated tools, I have this block of code in various classes:

```php
class MyCommand
{
    use EntityManagerManagerAwareTrait;
    /** @var string */
    private const NAME            = 'my:command:name';
    /** @var int */
    private const BATCH_SIZE = 100;
    /** @var string */
    protected static $defaultName = self::NAME;
...
```

How to add a blank line before each DocBlock?

```diff
class MyCommand
{
    use EntityManagerManagerAwareTrait;
+
    /** @var string */
    private const NAME            = 'my:command:name';
+
    /** @var int */
    private const BATCH_SIZE = 100;
+
    /** @var string */
    protected static $defaultName = self::NAME;
...
```

**Comment by julienfalque** [comment]
`class_attributes_separation` (kind of) does what you want: it adds a blank line between constants/properties/methods. Though it currently does it even when there is no DocBlock.

In v2.17 (to be released), `class_attributes_separation` options have been changed to be able to choose between 0 or 1 blank line instead of always 1. #5060 is a WIP to change this again so we choose between "always 1" or "1 if there is a DocBlock, 0 otherwise".

**Comment by SpacePossum** [comment]
The option has been released, however you are best of with `class_attributes_separation` with `elements` having `one` or `none`, both (including `none`) will add the empty line.
Let me know if there is still something left here and I'll reopen :+1:
