### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by boesing** [FriendsOfPHP/PHP-CS-Fixer#5130]
## Support question

Hey there,

`composer/semver` was added 2 months ago. Is there a plan for releasing a new version somewhen soon?

**Comment by SpacePossum** [comment]
Hi,
Next week Monday there is most likely a catch up with the members and this will be on the agenda, hope to have an answer soon!
I think the 2.15 and 2.16 releases should be good to go.

**Comment by ruudk** [comment]
I know you are busy, but any news on a new tagged release 🙏 ? I really want to use the latest hot features in 2.16.x. 😍

**Comment by SpacePossum** [comment]
Hi!
Thanks for the ping, however I'm not the one who does the releases in this project. We've missed some monthly team align meetings because of everything going on in peoples lives. I'll try to see if what we can do though, 'cause yeah I would love to see new releases, we've done so much since the last ones! :heart:

**Comment by drupol** [comment]
Can't wait for the next release as well :-)

**Comment by SpacePossum** [comment]
releases have been done :)
