### ISSUE TITLE
Class method argument type hints considered unused?

### ISSUE THREAD

**Issue by GPHemsley** [FriendsOfPHP/PHP-CS-Fixer#5168]
## Support question

If I have a class method with type hints and I add "use" statements for those type hints, php-cs-fixer will remove them due to no_unused_imports. However, these seem like they're being used to me. What am I missing?

(Note: I'm using Symfony and Doctrine, so there are all sorts of autoload things going on. Is this coming into play somehow?)

**Comment by SpacePossum** [comment]
Hi and thanks for your question!

With SF and Doctrine there can sure be a lot of magic going on :)
However, since a lot of people here know these stacks I wouldn't expect issues with these. Could you share a bit of sample code that is being changed incorrectly? (maybe together with the PHP version and PHP-CS-Fixer version and configuration you are using). Thanks!

**Comment by julienfalque** [comment]
The import of `BarTransformer` is not removed because it is considered unused but because it is superfluous: `BarTransformer` is declared in the same namespace as the one it is imported in, so the import statement isn't actually needed.

This topic is already discussed in #4159 so I'm closing here.
