### ISSUE TITLE
DocumentationTest - decide about future of disabled test

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#5209]
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5210
ref #3475

**Comment by julienfalque** [comment]
This test is the equivalent of what we had for `README.rst` before #3475. Though fixing this test will often require to have a specific version of PHP to generate the code diffs, like the current failure. If #5183 gets merged, we should also be able to get the expected diffs from the failure in the matching job (i.e. PHP 8 job here). We should keep the test and fix it IMO.

I have been using a custom Docker setup for months now, which helps in such situation. Do you want me to submit it in a PR?

**Comment by keradus** [comment]
let me start with earlier question - is it enough to say that we can run the test on PHP 7.4 only, and everything will work?
or we are in case when some content has to be generated on 7.0 and some on 7.4, for example ?

**Comment by julienfalque** [comment]
Generating diffs from code samples relies on running the fixers (like the `describe` command does) so each code sample that requires specific PHP versions can only be generated using those specific versions. This means there is currently no way to generate or check the documentation on a single version of PHP.

**Comment by SpacePossum** [comment]
I think there is value in the test, but it needs changes that might not be trivial. So if we want to know if the docs are up to date we need to (regex) checks the docs against the expected docs. But first... lets figure out how to generate those expected doc's.

With the changes PHP8.0 brings a fixer might have code fix samples for; lets say for example here; samples for PHP7.0 && > 7.4, 7.4 and < 8.0 and >= 8.0. This means that to generate the complete doc. it has to be generated on 3 versions and the results being merged (manually).

Than that result has be checked on at least these 3 PHP versions on the CI that validate only the samples applicable to the PHP it is running on and ignoring the samples it cannot validate.

Lucky there are not many cases and it doesn't effect runtime experience of the users if it is not 100%, yet it would be great to get it right :)

**Comment by keradus** [comment]
folks, generation doesn't need to be happening behind single command nor be directly tested as phpunit suite.

idea, in pseudocode
```
foreach ($rules as $rule)
    foreach ($phps as $php)
        php-$php generate-rule-samples $rule > $rule-$php.json

    combine-rule-samples $rule > $rule.json

generate-docs-from-jsons
```

different php-envs can be hidden behind docker and we can verify if the files are up to date by... regenerating the docs from scratch as separated CI job and checking whether any file got modified.

**Comment by julienfalque** [comment]
IMO the main issue we have to solve is "how can we check that code samples specific to version Y of PHP are correct when the tests run on version X".

Currently, the tests ignore those code samples when running on the wrong PHP version. That means that all we need is a CI job for all PHP versions we support so that all code samples are checked. And we (almost?) already have that setup.

Second issue might be when someone adds or updates one of those code samples but doesn't have the correct PHP version locally. In this case, the doc cannot be updated automatically and the contributor will have to either:

- figure out the diff and update the doc manually
- push the changes and get the diff from the CI failure
- let the maintainers take care of that

In all cases, I would say this is essentialy a DX issue that is easy enough to fix and should not happen often.

My point is that I would advise not to spend much time trying to setup a complicated test system for this because the issue is quite trivial IMO. The current tests are not perfect but they do the job.

On the other hand, having a complete Docker setup on the project would help: we could have a single script to run doc generation on all PHP versions at once. I'll submit a PR.

Also I see one possible improvement to the doc command: currently it puts something like "unable to generate the diff" for code samples on the wrong PHP version. We could instead try to parse the existing doc to use the diff if it was previously generated.

**Comment by keradus** [comment]
Thanks for great work on this topic, @julienfalque !
Closing the ticket due to merge of #5236 and #5209

**Comment by julienfalque** [comment]
By the way, we should do something about https://cs.symfony.com. @fabpot [You suggested to archive it](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3475#issuecomment-618052493), do you need us to do something regarding that?

**Comment by keradus** [comment]
i strongly believe that there should be a website. can be very minimalistic, but serves well as landing page, at least.
is domain the only concern?
