### ISSUE TITLE
GitlabReporter CodeQuality missing line location 

### ISSUE THREAD

**Issue by Patrick-Remy** [FriendsOfPHP/PHP-CS-Fixer#5352]
## Bug report

When using `php-cs-fixer fix --dry-run --format=gitlab` the output misses the related line positions.
E.g. in my case the output is:
```
[{"description":"braces","fingerprint":"852f181ff39f68c06a16a4f28b4bb81f","location":{"path":"test.php","lines":{"begin":0}}}]
```

I expected that `"lines":{"begin": ... }` was properly set [like specified here](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#locations) and results in something like

// from https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#code-quality-widget
![](https://docs.gitlab.com/ee/user/project/merge_requests/img/code_quality.png)

instead the related code section is empty
![Bildschirmfoto 2020-12-10 um 16 59 47](https://user-images.githubusercontent.com/20044441/101797278-23b97300-3b0a-11eb-965d-80ae84be4fc9.png)

### Code snippet that reproduces the problem

Any code snippet with any style error.

**Comment by SpacePossum** [comment]
Hi and thanks for your question.

It is not possible to bind the result of a single fixer/rule to a signle line, in some cases it can but in many it cannot. This is because of how the tool works where many fixers will move parts of the code around and fixers after these fixers make additional changes. Therefore there is no longer a one-to-one relation between a changed bit of code and one fixer.

**Comment by ttomdewit** [comment]
@SpacePossum Is this the case even when `--dry-run` is enabled? Surely the code isn't changed?

**Comment by SpacePossum** [comment]
Sadly yes, even than, the dry-run makes it so that the result is not written back to file. However the code gets changed internally and passed from one fixer to the other.
