### ISSUE TITLE
Wrong display of progress in 3.0.0

### ISSUE THREAD

**Issue by garak** [FriendsOfPHP/PHP-CS-Fixer#5683]
See attached screenshot

![screenshot](https://user-images.githubusercontent.com/179866/117127697-b948ee00-ad9c-11eb-8691-cb96ecae8019.png)

I guess that progress bar should be something like phpunit's one.

**Comment by kubawerlos** [comment]
Can you provide more details, like operating system and terminal? On my local PC as well as on GitHub action for the same commit that is on your screenshot ([here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/runs/2495852022)) progress looks fine.

**Comment by garak** [comment]
Ubuntu 21.04 with standard shell (bash)

**Comment by keradus** [comment]
@garak , did you run the tool and then resized the window? that's the only way so far that I managed to reproduce the issue

also, can you run the tool without docker to check whether it is related to it on your env?

**Comment by garak** [comment]
I tried various screen sizes, the length is always the same (so it's fitting only when large). I also tried to run directly on my machine (without docker), it's the same

**Comment by garak** [comment]
Sorry, I have to revert my last statement: indeed with local environment it's working as expected.

**Comment by garak** [comment]
I tried to change env `COLUMNS` in my docker configuration and I found that's is a bit better.
But maybe php-cs-fixer is counting too much on it? I think it should not go so wide (again, phpunit is a reference)

**Comment by keradus** [comment]
PHP CS Fixer is [relying](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/src/Console/Command/FixCommand.php#L299) on Symfony Component, and the `COLUMNS` env var is a [special configuration for it](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Console/Terminal.php#L27)

try to unset the env var.
- all good? then I would say nothing to do for us, we respect `COLUMNS` by design
- without env, the result is not so good? please raise the bug ticket to Symfony component that `getWidth` doesn't work nice in docker env

**Comment by garak** [comment]
I leave this just as a reference in case someone have the same problem:  I managed to get exactly the same width of phpunit by using `docker-compose exec -e COLUMNS=80 myimage php-cs-fixer fix -v`

**Comment by mfn** [comment]
FTR, I've had similar "bad" experiences with phpstan not doing this properly on some environments (in vagrant, for me) and also ended up hunting it down to symfony part stopped there and also couldn't find a clear recipe to reproduce this.

**Comment by mfn** [comment]
See https://github.com/phpstan/phpstan/issues/4180
