### ISSUE TITLE
"phpdoc_to_property_type" must support a confg option to convert only non-union type

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/PHP-CS-Fixer#5691]
## Bug report

```diff
class ConfigTrait
{
    /**
     * @param string|array $files  One or more filenames
     */
-    public function readConfig($files = ['config.php'], string $format = 'php')
+    public function readConfig(array $files = ['config.php'], string $format = 'php')
    {
    }
```

is not supported in php 7.4, a config option must be support - or better, CS Fixer should support some configuration option like "minimal php version"

## as the fix is even not 1:1 (union type is not honored at all), I propose to fix the rule to not relate union type at all

**Comment by julienfalque** [comment]
A "minimal php version" option would not help, the change is wrong here, `array` is not compatible with `string|array`, no matter the version of PHP.

I assumed you meant `phpdoc_to_param_type` rather than `phpdoc_to_property_type` but I was not able to reproduce the issue though, please provide information as requested in the issue report template (PHP version, PHP CS Fixer version, your configuration, ...).

**Comment by SpacePossum** [comment]
I cannot reproduce this on ~latest, please follow the issue template so we have the details needed to debug this. If we've details to work from/reproduce than I'm happy to reopen the issue.

**Comment by keradus** [comment]
@SpacePossum  , i was facing same issue in past, already fixed indeed ;)
