### ISSUE TITLE
[BC] drop alternative syntax by default for all build in fixers

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#6003]
On next major, lets drop alternative syntax by default for all build in fixers, with maybe exception like `EncodingFixer` or something. 
It is becoming harder and harder to go through all the paths each time PHP changes something in the syntax. Secondly, a lot of the fixers do not exclude alternative syntax but are lacking tests. We could write tests and fix all issues, but I prefer not to until reported by someone else and than just drop on next major.

**Comment by keradus** [comment]
what alternative syntax you have in mind?

**Comment by julienfalque** [comment]
I assume we're talking about alternative syntax for control structures, e.g. `if () { ... }` → `if (): ... endif;`. Maybe [introducing AlternativeSyntaxAnalyzer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5960/files#diff-e65e4861e89e9046d6b7893b7bbfef77f02b4ee623094a753103a3054694e110) could help? Otherwise I'm fine with dropping support for it.

**Comment by SpacePossum** [comment]
Indeed, things like `T_ENDSWITCH` etc. are a real pain, basically any control structure without braces likes:

```php
while ($i <= 10):
    echo $i;
    $i++;
endwhile;
```

as it makes requires a bunch more logic to keep track of the "depth" for example

**Comment by WinterSilence** [comment]
@SpacePossum 
>  lets drop alternative syntax by default for all build in fixers

How you planed do it? 

**I'm think better solution is add something like "risky rule" to mark fixes working with alternative syntax because in most case that's use only in "views" and views don't uses traditional syntax.**

> it makes requires a bunch more logic to keep track of the "depth" for example

The problem not : no high-level tools for working with code as with abstraction.
Need create high level API to work with language constructions or use something like [AST parser](https://github.com/nikic/php-parser) to parse code as nested tree
