### ISSUE TITLE
`phpdoc_types_order` bug with intersection type

### ISSUE THREAD

**Issue by kenjis** [FriendsOfPHP/PHP-CS-Fixer#6238]
## Bug report

v3.5.0

- intersection type is converted to union type

### Code snippet that reproduces the problem

```sh-session
$ tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src --diff
Loaded config default from ".../php-cs-fixer-test/.php-cs-fixer.php".
Using cache file ".php-cs-fixer.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
   1) src/MyPackage.php
      ---------- begin diff ----------
--- .../php-cs-fixer-test/src/MyPackage.php
+++ .../php-cs-fixer-test/src/MyPackage.php
@@ -8,7 +8,7 @@
 {
     public function test()
     {
-        /** @var MockObject&Query $query */
+        /** @var MockObject|Query $query */
         $query;
     }
 }

      ----------- end diff -----------
```

`.php-cs-fixer.php`:
```php
$config = new PhpCsFixer\Config();
return $config->setRules([
         '@PSR12' => true,
         'phpdoc_types_order' => [
             'null_adjustment' => 'always_last',
             'sort_algorithm'  => 'alpha',
         ],
    ])
    ->setFinder($finder)
    ;
```

**Comment by Jean85** [comment]
:+1: on this issue. It broke our CI `sentry-php`: https://github.com/getsentry/sentry-php/runs/4814501803?check_suite_focus=true#step:5:20

I'm trying to find the culprit in the changelog/diff...

**Comment by ruudk** [comment]
Same issue here... we want to keep our intersection types. I'll postpone the upgrade for now.

**Comment by Jean85** [comment]
I may have found the culprit: https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/6bf7ba5282dbbcfe67afa4e7c137cd74dcc66597#diff-de9d90510a6626bf0643e8978fbe25c91ff3fc48e61b0b5ccde5edd754bf70ccR389

I'll try to expand the tests to create a regression one

**Comment by Jean85** [comment]
Sorry I may not have all the knowledge to fix this, but I've at least ported the reproducer into a test: #6245

**Comment by Jean85** [comment]
Ok I've definitely found the culprit, and it's 8b8eca0a5ae5a11b7d61b0bd56f8744c52dd6747

The issue is that that change is not feasible at all: changing order of types without taking account of parentheses or mixes of `|` and `&` is a no-go: it could definitely change the meaning of the type expressed in the PHPDoc.

**Comment by kubawerlos** [comment]
@Jean85 you were going right direction, take a look at the fix: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6243.

In deed the root of problem was `implode` with `|` - it was not a problem in 3.4.0, because intersection types were not recognized at all, [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6188) fix (see changes in `src/DocBlock/TypeExpression.php`) added support for intersection types, but `Annotation::setTypes` was assuming it always be types alternation.
