### ISSUE TITLE
empty string passed to substr_compare produces warnings in AbstractPhpdocTypesFixer 

### ISSUE THREAD

**Issue by marcin-bulkiewicz1** [FriendsOfPHP/PHP-CS-Fixer#6323]
Hi, this problem came up when using ECS but refers to php-cs-fixer so I report here.

**PHP version**: 7.2
**php-cs-fixer version**: 3.6.0 (checked via PHP_CS_FIXER_IGNORE_ENV=-1 php vendor/symplify/easy-coding-standard/vendor/bin/php-cs-fixer -v)

```php
PHP Warning:  substr_compare(): The start position cannot exceed initial string length in /var/www/symfony/vendor/symplify/easy-coding-standard/vendor/friendsofphp/php-cs-fixer/src/AbstractPhpdocTypesFixer.php on line 105
```

Some empty strings are passed to the `normalizeType()` method so `\substr_compare($type, '[]', -\strlen('[]'))` produces warnings.

**Comment by SpacePossum** [comment]
Hi and thanks for reporting :+1: 

I assume this code is brought inline by some compiler/optimizer, which is pretty cool TBH, wonder where that happens.
Anyway, the code seems to be coming from here:
https://github.com/symfony/polyfill/blob/v1.24.0/src/Php80/Php80.php#L101

I've made a PR to patch the issue here: https://github.com/symfony/polyfill/pull/394
