### ISSUE TITLE
`no_unneeded_control_parentheses` breaks code

### ISSUE THREAD

**Issue by kevindierkx** [FriendsOfPHP/PHP-CS-Fixer#6472]
## Bug report

The `no_unneeded_control_parentheses` fixer is too gready. (v3.9.1)

### Code snippet that reproduces the problem

```php
SomeClass::{$method}(
    $variableA,
    $variableB
);
```

Will be formatted as:

```php
// Missing opening parentheses
SomeClass::{$method}
    $variableA,
    $variableB
);
```

Removing the curly braces would prevent the formatter from removing the parenthesis. 

---

[As mentioned by @PabloKowalczyk](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6472#issuecomment-1184014036)

[Explanation why this breaks by @Maikuolan](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6472#issuecomment-1184082309)

```php
<?php

$val = null;

var_dump((int) ($val ?? 1));

// Output: 1
```

Will be formatted as:

```php
<?php

$val = null;

var_dump((int) $val ?? 1);

// Output: 0
```

**Comment by keradus** [comment]
Hey @kevindierkx , thanks for letting us know!
Is this sth you experienced also on 3.8.x?

also, perhaps you could consider to raise a fix PR for this one?

**Comment by PabloKowalczyk** [comment]
@stof IMO it's not correct, https://3v4l.org/JPBdb

```php
<?php

$val = null;

var_dump((int) $val ?? 1);
var_dump((int) ($val ?? 1));
```
First `var_dump` outputs `0` and second `1`.

**Comment by Maikuolan** [comment]
Worth noting, for those that might forget, that null coalescence has a [low precedence](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce), and will likely need parenthesis whenever using it in combination with other expressions, operators, etc (and that being the reason for why at the above, the evaluation is different, due to null coalescence having a lower precedence than casts).

**Comment by stof** [comment]
@PabloKowalczyk your snippet did not contain any null-coalesce operator.

**Comment by PabloKowalczyk** [comment]
@stof I stand corrected, sorry.

**Comment by SpacePossum** [comment]
Thanks for reporting, I'll look into the `{}` cases, these are indeed touched incorrectly, my apologies for that.
I hope/expect to have a patch ready today or tomorrow.

For `??` and `?` operations, these have been left out for touching by design for now because of the complexity of (properly) evaluating the precedence of statements (especially when working with tokens only).
So if there this a bug report related to null-coalesce please let me me know :)
