### ISSUE TITLE
Are spaces meant to be added after named parameter names:

### ISSUE THREAD

**Issue by BladeMF** [FriendsOfPHP/PHP-CS-Fixer#6500]
I am not sure whether that's a bug or missing feature, or just me missing something but in this code:
```php
$this->useCase(
	featureAnalysisHistory:$featureAnalysisHistory
);
```
shouldn't there be a space after `featureAnalysisHistory:`?

**Comment by SpacePossum** [comment]
Hi and thanks for your question,

If you want a single space after the name part of the argument you can try the rule `single_space_after_construct`. Make sure that in your of the rule the `named_argument` is listed for the `constructs`. For example `"constructs": ["named_argument"]`, as it is not on by default because of BC policy.

For more details on the rule see [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.4/doc/rules/language_construct/single_space_after_construct.rst)

**Comment by BladeMF** [comment]
Thank you, that worked as I expected.
