### ISSUE TITLE
Clean STDOUT Needed for new Sublime Text 3 Plugin

### ISSUE THREAD

**Issue by TundraTech** [FriendsOfPHP/PHP-CS-Fixer#784]
Hi there, I've built a great new ST3 plugin for PHP-CS-FIXER.

Ive already built a multithreaded module for background processing, timer with animation in the status bar and a shadow copy live preview mode, with full recursive directory processing. Ive also set it up so you can easily adhere to the different coding standard specs, or customize each setting one by one, and also control output indentation (tabs or space and depth).

Wondering if PHP-CS-FIXER  is ever going to support STDOUT with the cleaned output. I know the dry run feature does but the plus and minus signs everywhere make the string useless.It can't be that difficult for someone to implement a return string switch vs writing to a file with the processed input? At some point the clean string must be captured in the source code yes?

My plugin is working fantastic as is but the lack of STDOUT forces it to run through this process, which causes a significant hit on performance: 

 -create a copy of the source file
 -clean tabs / whitespace (php-cs-fixer doesn't seem to like it when you use non 4 space tabs)
 -run php-cs-fixer on clean file
 -load the cleaned file back into sublime text
 -delete the temp copy

Im running a very fast SSD system, currently process times are about 4 seconds for 1500 lines of code. On HDD system i suspect this would be a lot slower though, however doing all processing completely in memory would give near native performance I'm sure...

I would really like to release this plugin ASAP.

If php-cs-fixer could support STDOUT, performance would improve drastically.

Any hope for this?

**Comment by sampablokuper** [comment]
At time of writing, **this issue has not been fixed.**

However, it should remain closed: not because it has been fixed (to repeat: it has not been), but because it is a duplicate of #454.

Further remarks about this issue should therefore ideally be posted at #454.

**Comment by keradus** [comment]
To clarify - this raised issue was not closed because it was resolved, but due to lack of interest in it.

**Comment by keradus** [comment]
Yes, we do close duplicates faster.
Can't agree with you at all. We did not closed them out of the blue, some work had been done on that, discussion were made.
Also, 8 ppl are not that many compared to all users. Don't you even try to convince me that, if you were the only guy since last 2 years. And in 2014 tool works way different than novadays, offering less ways of reporting. 
Finally, request was not denied, it was approved with "if you want it, bring it to the table". In the end, nobody did, issues(/feature requests) were closed due to house cleaning and inactivity of them.

If your main post had been answered damn good and thread was locked, don't spam other threads as well.

Answered in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/454#issuecomment-395670023 .
Whole discussion of yours brings no other value than "I want this feature" voice. And ultimate answer you got is straight forward - "go ahead and raise a PR".

Closing due to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/454#issuecomment-395723915
