### ISSUE TITLE
Option's deprecation warning is misplaced in docs

### ISSUE THREAD

**Issue by staabm** [FriendsOfPHP/PHP-CS-Fixer#7903]
the deprecation warning seems off on

https://cs.symfony.com/doc/rules/function_notation/nullable_type_declaration_for_default_null_value.html

Firefox

![grafik](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/120441/6f52fa36-8352-4982-82e3-0db1acf505c3)

Chrome

![grafik](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/120441/82b91770-9192-411b-9e55-efd1cefec1a1)

**Comment by gagan2125** [comment]
kindly use other method to perform that function, otherwise in future it will be problem and it won't work

**Comment by Wirone** [comment]
@gagan2125 it's not about the intent of deprecation (which is clear), but about the placing of the warning. On mobile it's actually invisible, because it's over the header:

![Screenshot_2024-03-22-10-29-02-898_com.android.chrome-edit.jpg](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/d3a5973a-a1df-4fc6-9ec2-abb6cb8b7209)

It just should be somewhere inline in the docs.

**Comment by staabm** [comment]
> It just should be somewhere inline in the docs.

👍

**Comment by Wirone** [comment]
It's fixed now:

<img width="1728" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/fbacb2ff-d57b-47a2-9359-7657bae3b923">

Please note it's a quick fix, we need proper support for Sphinx' admonitions. We bumped Sphinx version at some point and it probably changed the output DOM for them, because our style stopped working. I would love to see better style for them though (like [here](https://sphinx-book-theme.readthedocs.io/en/stable/reference/kitchen-sink/admonitions.html)).

**Comment by gagan2125** [comment]
Good job
Note it
