### ISSUE TITLE
Question: PSR0

### ISSUE THREAD

**Issue by keradus** [FriendsOfPHP/PHP-CS-Fixer#858]
I suggest to turn off PSR0 fixer from cascading PSR group (currently using PSR2 uses PSR1 and PSR0 as well). PSR0 was deprecated and in fact when using PSR4 I must disable PSR0 fixer.

This should be done after #857.

What do you think guys ?

**Comment by stof** [comment]
I disagree with the point 3 though. the PSR-0 Fixer is currently a risky one (probably the most risky of all our fixers because instead of breaking your code, it has the power of breaking other projects depending on your code by introducing BC breaks in your libraries). The PSR-4 fixer would also be risky for the exact same reasons. So it should stay disabled by default.

**Comment by SpacePossum** [comment]
> 1) We definitely need separate fixers, no question about that - we're all agreed there.
> 2) We should definitely disable psr0 by default - we're all agreed there.
> 3) We should probably enable psr4 by default - I like this, but I'm not sure if there is total agreement.
> 4) I think we should remove the psr0 fixer in 2.0 - other people think we should just keep it.

1,2, :+1:  3,4 :-1:   :)

btw. I think this talk together with https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/857 comes to a conclusion for: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/117

**Comment by localheinz** [comment]
@keradus 

:+1:
